/* ═══════════════════════════════════════════════════════════════
   VOYARA · Demo dataset (DEMO MODE)
   Structured mock JSON used when CONFIG.MODE === "demo" or when
   live API keys are absent. Same shape the live services return.
   ═══════════════════════════════════════════════════════════════ */

const IMG = (seed, w = 800, h = 600) => `https://picsum.photos/seed/${seed}/${w}/${h}`;

/* ---------- City catalogue ---------- */
const CITIES = [
  {
    id: "paris", name: "Paris", country: "France", countryCode: "FR",
    lat: 48.8566, lng: 2.3522, tz: "Europe/Paris", currency: "EUR", language: "French",
    languageCode: "fr", flag: "🇫🇷", population: "2.16M", plug: "Type E · 230V",
    emergency: { police: "17", ambulance: "15", fire: "18", general: "112" },
    visa: "Schengen — visa-free 90 days for EU/US/UK/CA/AU citizens.",
    tagline: "The city of light — art, revolution and effortless romance on the Seine.",
    hero: IMG("voyara-paris", 1800, 1000),
    score: { safety: 72, weather: 68, cost: 45, attractions: 96, access: 90 },
    bestSeason: "April – June",
    monthScores: [2,2,3,4,4,3,2,2,3,3,2,1], // 0 poor .. 4 excellent
    monthLabels: ["Cold","Cold","Mild","Blossom","Blossom","Pleasant","Warm","Warm","Pleasant","Mild","Cool","Festive"],
    costBase: { hotel: [95, 210, 540], food: [32, 62, 130], transport: 9, attractions: 22, activities: 35, shopping: 25 },
    weatherSeed: { temp: 14, condition: "Partly Cloudy", icon: "⛅", humidity: 66, wind: 14, vis: 10, sunrise: "07:42", sunset: "19:58" },
    safety: {
      level: "green", label: "Normal",
      advisory: "Exercise normal precautions. Petty theft (pickpocketing) is common near major tourist sites and metro hubs.",
      source: "Demo advisory · verify with your foreign ministry",
      updated: "2026-10-05T09:00:00Z",
      alerts: [
        { sev: "yellow", title: "Pickpocket activity reported", text: "Elevated reports around Eiffel Tower, Louvre and Gare du Nord. Keep bags zipped and in front.", where: "1st, 7th, 10th arrondissements", time: "2026-10-04T18:20:00Z", src: "City Police bulletin" },
        { sev: "green", title: "Transport running normally", text: "Metro, RER and SNCF operating on schedule. Minor works on Line 4 at night.", where: "Metro network", time: "2026-10-05T07:00:00Z", src: "RATP" },
      ],
    },
    transport: {
      airports: [{ name: "Charles de Gaulle (CDG)", status: "open", note: "All terminals operational. Allow extra 30 min at security." }],
      trains: "SNCF national rail operating normally. TGV on time >92%.",
      summary: "You can travel to Paris right now — airports open, rail normal, no border restrictions.",
    },
    etiquette: [
      { mark: "ok", topic: "Greetings", text: "A light handshake or “Bonjour” when entering shops. Always greet before asking anything." },
      { mark: "ok", topic: "Dining", text: "Keep hands on the table (not elbows). Saying “Bon appétit” is customary. Tipping 5–10% is appreciated, not required." },
      { mark: "care", topic: "Dress", text: "Parisians dress sharply. Smart-casual fits in everywhere; sportswear reads as tourist." },
      { mark: "care", topic: "Language", text: "Open with “Bonjour, parlez-vous anglais ?” — attempting French first goes a long way." },
      { mark: "no", topic: "Louvre & museums", text: "No flash photography; food and large bags are not allowed in galleries." },
      { mark: "no", topic: "Metro", text: "Avoid loud phone conversations; keep luggage clear of doors during rush hour." },
    ],
    goodToKnow: [
      "Museums are closed on Tuesdays (Louvre) or Mondays (Orsay) — plan around it.",
      "Tap water is safe; ask for “une carafe d'eau” — it's free.",
      "Many shops close between 13:00–15:00 in smaller neighborhoods.",
      "Validate nothing on metro — just tap your Navigo/contactless card.",
    ],
    places: [
      { id: "p-louvre", cat: "museum", name: "Louvre Museum", desc: "The world's largest art museum and a historic palace — home to the Mona Lisa and 35,000 works.", img: IMG("louvre-int"), rating: 4.8, price: "€24", hours: "09:00–18:00 (Tue closed)", dist: "1.2 km", lat: 48.8606, lng: 2.3376, unesco: true, visit: "3–4 hours",
        artworks: [
          { name: "Mona Lisa", period: "c. 1503–1519", origin: "Italian Renaissance", img: IMG("mona"), sig: "Leonardo da Vinci's portrait revolutionized painting with sfumato technique and psychological depth.", fact: "It was stolen in 1911, which made it the most famous painting on Earth." },
          { name: "Winged Victory of Samothrace", period: "c. 200–190 BC", origin: "Ancient Greece", img: IMG("nike"), sig: "A masterpiece of Hellenistic sculpture, commemorating a naval victory.", fact: "It was discovered in 1863, in over 200 fragments, on the island of Samothrace." },
          { name: "Venus de Milo", period: "c. 150–125 BC", origin: "Ancient Greece", img: IMG("venus"), sig: "Icon of idealized feminine beauty and one of the most copied statues in history.", fact: "Her missing arms were lost when the statue was found on Melos in 1820." },
        ] },
      { id: "p-eiffel", cat: "monument", name: "Eiffel Tower", desc: "Gustave Eiffel's 330 m iron lattice — the definitive symbol of Paris, built for the 1889 World's Fair.", img: IMG("eiffel-tower"), rating: 4.7, price: "€29.10", hours: "09:30–23:00", dist: "4.8 km", lat: 48.8584, lng: 2.2945,
        artworks: [
          { name: "The Iron Lady", period: "1887–1889", origin: "Industrial Revolution France", img: IMG("eiffel2"), sig: "A structural engineering triumph that was meant to stand only 20 years.", fact: "It grows about 15 cm taller in summer due to thermal expansion." },
        ] },
      { id: "p-orsay", cat: "museum", name: "Musée d'Orsay", desc: "Great Impressionist and Post-Impressionist collection inside a Beaux-Arts railway station.", img: IMG("orsay"), rating: 4.8, price: "€17", hours: "09:30–18:00 (Mon closed)", dist: "2.0 km", lat: 48.8600, lng: 2.3266, visit: "2–3 hours",
        artworks: [
          { name: "Starry Night Over the Rhône", period: "1888", origin: "Post-Impressionism", img: IMG("starry"), sig: "Van Gogh's meditation on gaslight, reflection and the night sky.", fact: "Painted on the banks of the Rhône in Arles, before his famous ear incident." },
          { name: "Bal du moulin de la Galette", period: "1876", origin: "Impressionism", img: IMG("renoir"), sig: "Renoir's sun-dappled Sunday dance scene — Impressionism at its most joyful.", fact: "Two versions exist; this larger one hangs in Paris." },
        ] },
      { id: "p-notredame", cat: "religious", name: "Notre-Dame Cathedral", desc: "Gothic masterpiece on Île de la Cité — reopened in 2024 after the 2019 fire.", img: IMG("notredame"), rating: 4.8, price: "Free (tower extra)", hours: "07:45–19:00", dist: "1.4 km", lat: 48.8530, lng: 2.3499, unesco: true },
      { id: "p-montmartre", cat: "neighborhood", name: "Montmartre & Sacré-Cœur", desc: "Bohemian hilltop village of painters, cabarets and the white basilica overlooking Paris.", img: IMG("montmartre"), rating: 4.6, price: "Free", hours: "Always open", dist: "4.1 km", lat: 48.8867, lng: 2.3431 },
      { id: "p-versailles", cat: "ancient", name: "Palace of Versailles", desc: "Sun King's gilded palace, Hall of Mirrors and royal gardens — a day trip into absolutism.", img: IMG("versailles"), rating: 4.7, price: "€32", hours: "09:00–18:30", dist: "21 km", lat: 48.8049, lng: 2.1204, unesco: true },
    ],
    experiences: [
      { id: "x-seine", cat: "Nature", name: "Seine Evening Cruise", desc: "Glide past illuminated monuments aboard a glass-canopy boat.", img: IMG("seine"), rating: 4.7, price: "€18", hours: "10:00–22:30", dist: "0.8 km", lat: 48.8600, lng: 2.2870 },
      { id: "x-disney", cat: "Entertainment", name: "Disneyland Paris", desc: "Europe's most-visited theme park — two parks, one magical day.", img: IMG("disney"), rating: 4.5, price: "€62", hours: "09:30–21:00", dist: "42 km", lat: 48.8722, lng: 2.7758 },
      { id: "x-luxembourg", cat: "Nature", name: "Luxembourg Gardens", desc: "The city's most beloved park — chess players, pony rides, beehives.", img: IMG("luxembourg"), rating: 4.8, price: "Free", hours: "07:30–21:30", dist: "2.2 km", lat: 48.8462, lng: 2.3372 },
      { id: "x-moulin", cat: "Nightlife", name: "Moulin Rouge Cabaret", desc: "The original can-can cabaret in Pigalle, since 1889.", img: IMG("moulin"), rating: 4.4, price: "€87", hours: "Shows 19:00/21:00", dist: "4.5 km", lat: 48.8842, lng: 2.3323 },
      { id: "x-marais", cat: "Nightlife", name: "Le Marais Food Walk", desc: "Falafel on Rue des Rosiers, patisseries and hidden courtyards.", img: IMG("marais"), rating: 4.6, price: "€25", hours: "Self-guided", dist: "1.6 km", lat: 48.8570, lng: 2.3620 },
      { id: "x-bateaux", cat: "Family", name: "Cité des Sciences", desc: "Europe's largest science museum — planetarium and kids' city.", img: IMG("cite-science"), rating: 4.5, price: "€13", hours: "09:30–18:00", dist: "6.9 km", lat: 48.8956, lng: 2.3876 },
    ],
    hotels: [
      { id: "h-le-bristol", name: "Le Bristol Paris", stars: 5, rating: 9.4, price: 2450, dist: "3.1 km", area: "8th arrondissement", amenities: ["Spa", "Pool", "Michelin dining", "Pet friendly"], img: IMG("bristol") },
      { id: "h-marais-boutique", name: "Hôtel du Marais Boutique", stars: 4, rating: 8.7, price: 290, dist: "0.4 km", area: "Le Marais", amenities: ["Breakfast", "Bar", "Wi-Fi"], img: IMG("maraishotel") },
      { id: "h-latour", name: "Hôtel La Tour Eiffel", stars: 4, rating: 8.2, price: 340, dist: "0.6 km", area: "7th arrondissement", amenities: ["Rooftop", "Breakfast", "Wi-Fi"], img: IMG("eiffelhotel") },
      { id: "h-montmartre-inn", name: "Montmartre Inn", stars: 3, rating: 7.9, price: 130, dist: "4.2 km", area: "Montmartre", amenities: ["Wi-Fi", "Breakfast"], img: IMG("montmartrehotel") },
      { id: "h-riverside", name: "Riverside Saint-Michel", stars: 3, rating: 7.6, price: 115, dist: "0.9 km", area: "Latin Quarter", amenities: ["Wi-Fi"], img: IMG("latinhotel") },
      { id: "h-palais-royal", name: "Palais Royal Grand", stars: 5, rating: 9.1, price: 1280, dist: "1.0 km", area: "1st arrondissement", amenities: ["Spa", "Pool", "Concierge", "Bar"], img: IMG("royalhotel") },
    ],
    hospitals: [
      { name: "Hôtel-Dieu AP-HP", type: "Hospital · ER", address: "1 Place du Parvis Notre-Dame", lat: 48.8544, lng: 2.3470, open: "24/7" },
      { name: "American Hospital of Paris", type: "Hospital · ER", address: "63 Bd Victor Hugo, Neuilly", lat: 48.8838, lng: 2.2750, open: "24/7" },
      { name: "Pharmacie des Halles", type: "Pharmacy", address: "10 Rue de la Ferronnerie", lat: 48.8608, lng: 2.3472, open: "08:30–21:00" },
      { name: "Police Préfecture", type: "Police", address: "Île de la Cité", lat: 48.8555, lng: 2.3451, open: "24/7" },
      { name: "Caserne de la Cité (Pompiers)", type: "Fire", address: "6 Rue de la Cité", lat: 48.8549, lng: 2.3479, open: "24/7" },
    ],
    news: [
      { cat: "Events", title: "Nuit Blanche returns with 200 art installations across the city", src: "Paris Culture Desk", time: "2026-10-03T08:00:00Z", img: IMG("nuit"), sum: "The all-night contemporary art festival takes over bridges, museums and metro stations on the first Saturday of October." },
      { cat: "Transport", title: "Metro Line 4 fully automated — capacity up 20%", src: "RATP Journal", time: "2026-09-28T10:12:00Z", img: IMG("metro4"), sum: "The final driverless trains entered service, cutting peak-hour waits to under 2 minutes." },
      { cat: "Travel", title: "Louvre extends Friday late openings until 21:45", src: "Museum Weekly", time: "2026-09-25T14:40:00Z", img: IMG("louvrenight"), sum: "Evening access will now run year-round; night entries included with standard ticket." },
      { cat: "Weather", title: "Mild autumn forecast — golden October ahead", src: "Météo France", time: "2026-10-01T06:30:00Z", img: IMG("paris-autumn"), sum: "Temperatures 2°C above seasonal average with below-average rainfall through mid-month." },
    ],
    events: [
      { day: 18, mon: "Oct", title: "Nuit Blanche — All-Night Art Festival", where: "City-wide", time: "19:00 → sunrise", price: "Free", cat: "Cultural" },
      { day: 24, mon: "Oct", title: "Paris Jazz Festival — Closing Concert", where: "Parc Floral", time: "20:00", price: "€35", cat: "Concert" },
      { day: "1–9", mon: "Nov", title: "FIAC Contemporary Art Fair", where: "Grand Palais", time: "11:00–20:00", price: "€42", cat: "Exhibition" },
      { day: 11, mon: "Nov", title: "Armistice Day Ceremonies", where: "Arc de Triomphe", time: "09:00", price: "Free", cat: "Public holiday" },
    ],
  },

  {
    id: "kyoto", name: "Kyoto", country: "Japan", countryCode: "JP",
    lat: 35.0116, lng: 135.7681, tz: "Asia/Tokyo", currency: "JPY", language: "Japanese",
    languageCode: "ja", flag: "🇯🇵", population: "1.46M", plug: "Type A/B · 100V",
    emergency: { police: "110", ambulance: "119", fire: "119", general: "110" },
    visa: "Visa-free 90 days for many nationalities; others must apply in advance.",
    tagline: "Japan's ancient capital — a thousand temples, whispering bamboo and the art of tea.",
    hero: IMG("voyara-kyoto", 1800, 1000),
    score: { safety: 93, weather: 74, cost: 55, attractions: 94, access: 82 },
    bestSeason: "March – May",
    monthScores: [3,3,4,4,3,1,1,1,2,3,3,3],
    monthLabels: ["Cold","Plum bloom","Sakura","Sakura","Fresh","Rainy","Humid","Humid","Warm","Pleasant","Autumn","Quiet"],
    costBase: { hotel: [70, 160, 480], food: [28, 55, 150], transport: 7, attractions: 12, activities: 40, shopping: 30 },
    weatherSeed: { temp: 19, condition: "Clear Sky", icon: "☀️", humidity: 58, wind: 8, vis: 12, sunrise: "05:58", sunset: "17:32" },
    safety: {
      level: "green", label: "Normal",
      advisory: "Exercise normal precautions. Kyoto is among the world's safest large cities; the main risks are natural (typhoons, earthquakes).",
      source: "Demo advisory · verify with your foreign ministry",
      updated: "2026-10-05T09:00:00Z",
      alerts: [
        { sev: "green", title: "No security incidents", text: "No incidents affecting visitors reported in the past 30 days.", where: "City-wide", time: "2026-10-05T07:30:00Z", src: "Kyoto Pref. Police" },
        { sev: "yellow", title: "Typhoon season advisory", text: "October is late typhoon season. Monitor forecasts; trains may suspend service during storms.", where: "Kansai region", time: "2026-10-02T03:00:00Z", src: "JMA" },
      ],
    },
    transport: {
      airports: [{ name: "Kansai Intl (KIX)", status: "open", note: "Operating normally. Haruka Express 80 min to Kyoto Station." }],
      trains: "JR, Hankyu, Keihan and subway all operating normally.",
      summary: "You can travel to Kyoto right now — airport open, rail normal, no disruptions.",
    },
    etiquette: [
      { mark: "ok", topic: "Greetings", text: "A small bow is the default greeting; a nod and smile work for visitors." },
      { mark: "ok", topic: "Onsen", text: "Wash thoroughly before entering the bath. Tattoos: check first — some onsen still restrict them." },
      { mark: "care", topic: "Temples", text: "Dress modestly, remove shoes where indicated, and never touch or photograph geisha/maiko without consent." },
      { mark: "care", topic: "Tipping", text: "There is no tipping — it can cause confusion. Instead, say “gochisousama deshita” after meals." },
      { mark: "no", topic: "Trains", text: "Don't talk on the phone or eat while walking. Queue precisely at platform markings." },
      { mark: "no", topic: "Chopsticks", text: "Never stick chopsticks upright in rice or pass food chopstick-to-chopstick — both are funeral rituals." },
    ],
    goodToKnow: [
      "Carry some cash — many small temples and restaurants are cash-only.",
      "Buy a bus day pass; buses cover most sights better than trains.",
      "Temples open early (often 06:00) — go at dawn to beat crowds.",
      "Convenience stores (konbini) are excellent for cheap, quality meals.",
    ],
    places: [
      { id: "k-fushimi", cat: "religious", name: "Fushimi Inari Shrine", desc: "10,000 vermilion torii gates winding up a sacred mountain — dedicated to the fox deity Inari.", img: IMG("fushimi"), rating: 4.8, price: "Free", hours: "Always open", dist: "4.7 km", lat: 34.9671, lng: 135.7727, unesco: true,
        artworks: [
          { name: "The 10,000 Torii", period: "711 AD – present", origin: "Shinto tradition", img: IMG("torii"), sig: "Each gate is donated by a business praying for prosperity — names carved on the back.", fact: "The full mountain loop takes about 2–3 hours on foot." },
        ] },
      { id: "k-kinkaku", cat: "religious", name: "Kinkaku-ji (Golden Pavilion)", desc: "A Zen temple whose top two floors are covered in gold leaf, mirrored in a tranquil pond.", img: IMG("kinkaku"), rating: 4.7, price: "¥500", hours: "09:00–17:00", dist: "8.3 km", lat: 35.0394, lng: 135.7292, unesco: true,
        artworks: [
          { name: "Shariden (Relic Hall)", period: "rebuilt 1955", origin: "Muromachi period", img: IMG("kinkaku2"), sig: "The pavilion houses relics of the Buddha; the gold symbolizes purity against death.", fact: "A monk burned it down in 1950 — the story inspired Mishima's novel The Temple of the Golden Pavilion." },
        ] },
      { id: "k-arashiyama", cat: "nature", name: "Arashiyama Bamboo Grove", desc: "A cathedral of swaying bamboo in Kyoto's western mountains, beside the Hozu river.", img: IMG("bamboo"), rating: 4.6, price: "Free", hours: "Always open", dist: "11 km", lat: 35.0170, lng: 135.6710 },
      { id: "k-gion", cat: "neighborhood", name: "Gion Historic District", text: "Geisha district of wooden machiya houses, lantern-lit lanes and the Shirakawa canal.", name2: "", desc: "Geisha district of wooden machiya houses, lantern-lit lanes and tea houses.", img: IMG("gion"), rating: 4.6, price: "Free", hours: "Always open", dist: "3.2 km", lat: 35.0037, lng: 135.7754 },
      { id: "k-nijo", cat: "ancient", name: "Nijō Castle", desc: "The shogun's Kyoto residence — nightingale floors that sing, and golden screens of tigers.", img: IMG("nijo"), rating: 4.6, price: "¥1,030", hours: "08:45–17:00", dist: "2.9 km", lat: 35.0142, lng: 135.7482, unesco: true },
      { id: "k-philosophers", cat: "nature", name: "Philosopher's Path", desc: "A cherry-tree-lined canal walk connecting Ginkaku-ji to the neighborhoods of thinkers.", img: IMG("philosopher"), rating: 4.5, price: "Free", hours: "Always open", dist: "4.0 km", lat: 35.0272, lng: 135.7953 },
    ],
    experiences: [
      { id: "kx-tea", cat: "Entertainment", name: "Traditional Tea Ceremony", desc: " whisked matcha in a 100-year-old tea house near Kodai-ji.", img: IMG("tea"), rating: 4.9, price: "¥3,500", hours: "Sessions 10:00–16:00", dist: "3.4 km", lat: 35.0000, lng: 135.7800 },
      { id: "kx-monkey", cat: "Nature", name: "Arashiyama Monkey Park", desc: "200 free-roaming macaques on a mountain top with a panoramic Kyoto view.", img: IMG("monkey"), rating: 4.5, price: "¥600", hours: "09:00–16:30", dist: "11 km", lat: 35.0165, lng: 135.6735 },
      { id: "kx-kimono", cat: "Adventure", name: "Kimono Stroll & Old Town", desc: "Rent a kimono and wander Sannenzaka's preserved Edo-period lanes.", img: IMG("kimono"), rating: 4.7, price: "¥4,000", hours: "Shops 09:00–18:00", dist: "3.6 km", lat: 34.9985, lng: 135.7800 },
      { id: "kx-pontocho", cat: "Nightlife", name: "Pontocho Alley Dinner", desc: "Kyoto's most atmospheric dining lane — riverside terraces in summer.", img: IMG("pontocho"), rating: 4.6, price: "¥8,000+", hours: "17:00–23:00", dist: "2.6 km", lat: 35.0045, lng: 135.7706 },
      { id: "kx-hozu", cat: "Adventure", name: "Hozu River Rafting", desc: "Gentle rapids through the Arashiyama gorge — traditional boatmen included.", img: IMG("hozu"), rating: 4.7, price: "¥5,500", hours: "09:00 / 13:00 tours", dist: "12 km", lat: 35.0155, lng: 135.6680 },
      { id: "kx-aquarium", cat: "Family", name: "Kyoto Aquarium", desc: "River-themed aquarium with giant salamanders and dolphin shows.", img: IMG("kaiyukan"), rating: 4.3, price: "¥2,050", hours: "10:00–18:00", dist: "4.3 km", lat: 34.9875, lng: 135.7470 },
    ],
    hotels: [
      { id: "kh-ritz", name: "The Ritz-Carlton Kyoto", stars: 5, rating: 9.3, price: 1100, dist: "2.0 km", area: "Kamogawa river", amenities: ["Spa", "Michelin dining", "River view"], img: IMG("ritzkyoto") },
      { id: "kh-ryokan", name: "Nazuna Gosho Ryokan", stars: 4, rating: 9.0, price: 420, dist: "1.8 km", area: "Central Kyoto", amenities: ["Private onsen", "Kaiseki dinner", "Garden"], img: IMG("ryokan") },
      { id: "kh-gion-hotel", name: "Hotel Gion Machiya", stars: 3, rating: 8.4, price: 160, dist: "3.1 km", area: "Gion", amenities: ["Breakfast", "Wi-Fi"], img: IMG("gionhotel") },
      { id: "kh-station", name: "Kyoto Station Hotel", stars: 4, rating: 8.6, price: 190, dist: "0.2 km", area: "Kyoto Station", amenities: ["Onsen", "Breakfast", "Wi-Fi"], img: IMG("stationhotel") },
      { id: "kh-capsule", name: "Nine Hours Capsule", stars: 2, rating: 8.1, price: 38, dist: "0.5 km", area: "Downtown", amenities: ["Wi-Fi", "Lockers"], img: IMG("capsule") },
      { id: "kh-hanare", name: "Hanare Design Hotel", stars: 4, rating: 8.9, price: 240, dist: "5.5 km", area: "Yanaka district", amenities: ["Breakfast", "Gallery", "Wi-Fi"], img: IMG("hanare") },
    ],
    hospitals: [
      { name: "Kyoto University Hospital", type: "Hospital · ER", address: "54 Shogoin Kawahara-cho", lat: 35.0270, lng: 135.7810, open: "24/7" },
      { name: "Kyoto City Hospital", type: "Hospital · ER", address: "1-2 Higashi-Takada-cho, Mibu", lat: 34.9950, lng: 135.7400, open: "24/7" },
      { name: "Nishiki Pharmacy", type: "Pharmacy", address: "Nishiki Market", lat: 35.0050, lng: 135.7648, open: "09:00–20:00" },
      { name: "Nakagyo Police Station", type: "Police", address: "408 Hokomatsubara-cho", lat: 35.0035, lng: 135.7590, open: "24/7" },
    ],
    news: [
      { cat: "Events", title: "Jidai Matsuri — Festival of Ages parade returns October 22", src: "Kyoto Tourism", time: "2026-10-01T09:00:00Z", img: IMG("jidai"), sum: "2,000 costumed participants recreate 1,100 years of Kyoto history in the year's grandest pageant." },
      { cat: "Travel", title: "Kiyomizu-dera opens new night illumination season", src: "Temple Times", time: "2026-09-30T11:00:00Z", img: IMG("kiyomizu"), sum: "The wooden stage will be lit until 21:30 on weekends through late November." },
      { cat: "Transport", title: "Randen tram line adds English announcements", src: "Keifuku Rail", time: "2026-09-22T08:30:00Z", img: IMG("randen"), sum: "All Arashiyama-line trams now feature four-language onboard guidance." },
      { cat: "Weather", title: "First autumn colors forecast for mid-November", src: "JMA Kyoto", time: "2026-10-04T05:00:00Z", img: IMG("momiji"), sum: "Maple season expected to peak one week later than average this year." },
    ],
    events: [
      { day: 18, mon: "Oct", title: "Kamo River Moon Viewing (Tsukimi)", where: "Kamogawa Delta", time: "18:00–21:00", price: "Free", cat: "Cultural" },
      { day: 22, mon: "Oct", title: "Jidai Matsuri — Festival of Ages", where: "Imperial Palace → Heian Shrine", time: "12:00", price: "Free", cat: "Festival" },
      { day: "25–27", mon: "Oct", title: "Arashiyama Lantern Festival", where: "Arashiyama", time: "17:00–21:00", price: "Free", cat: "Seasonal" },
      { day: "3", mon: "Nov", title: "Culture Day — free museum entry", where: "City museums", time: "All day", price: "Free", cat: "Public holiday" },
    ],
  },

  {
    id: "dubai", name: "Dubai", country: "United Arab Emirates", countryCode: "AE",
    lat: 25.2048, lng: 55.2708, tz: "Asia/Dubai", currency: "AED", language: "Arabic",
    languageCode: "ar", flag: "🇦🇪", population: "3.6M", plug: "Type G · 230V",
    emergency: { police: "999", ambulance: "998", fire: "997", general: "999" },
    visa: "Visa on arrival (30–90 days) for 70+ nationalities; e-visa available otherwise.",
    tagline: "A desert mirage made real — the world's tallest tower, gold souks and futuristic islands.",
    hero: IMG("voyara-dubai", 1800, 1000),
    score: { safety: 88, weather: 52, cost: 60, attractions: 85, access: 92 },
    bestSeason: "November – March",
    monthScores: [4,4,4,3,1,0,0,0,0,1,3,4],
    monthLabels: ["Perfect","Perfect","Perfect","Warm","Hot","Very hot","Extreme","Extreme","Very hot","Hot","Pleasant","Ideal"],
    costBase: { hotel: [90, 220, 700], food: [35, 70, 180], transport: 12, attractions: 40, activities: 70, shopping: 45 },
    weatherSeed: { temp: 36, condition: "Clear Sky", icon: "☀️", humidity: 48, wind: 16, vis: 10, sunrise: "06:12", sunset: "17:55" },
    safety: {
      level: "green", label: "Normal",
      advisory: "Exercise normal precautions. Dubai has very low violent crime; laws are strict — know the rules on alcohol, photography and public behavior.",
      source: "Demo advisory · verify with your foreign ministry",
      updated: "2026-10-05T09:00:00Z",
      alerts: [
        { sev: "yellow", title: "Extreme heat advisory", text: "Feels-like temperatures above 42°C midday. Schedule outdoor activities before 10:00 or after 17:00.", where: "Emirate-wide", time: "2026-10-05T06:00:00Z", src: "NCM (met office)" },
        { sev: "green", title: "Metro & tram normal", text: "All lines operating; Dubai Metro now runs until 01:00 on weekends.", where: "Dubai Metro", time: "2026-10-04T22:00:00Z", src: "RTA Dubai" },
      ],
    },
    transport: {
      airports: [{ name: "Dubai Intl (DXB)", status: "open", note: "All terminals operational. Concourse D busy 20:00–01:00." }],
      trains: "Metro Red & Green lines normal; tram operating in Marina.",
      summary: "You can travel to Dubai right now — DXB open, all public transport normal.",
    },
    etiquette: [
      { mark: "ok", topic: "Dress", text: "Light modest clothing is fine; beachwear belongs at pools and beaches. Cover shoulders/knees in malls and old Dubai." },
      { mark: "ok", topic: "Greetings", text: "“As-salamu alaykum” is warmly received. Handshakes: wait for the local to extend first — some prefer not to shake with the opposite gender." },
      { mark: "care", topic: "Photography", text: "Never photograph people (especially women) without consent, and never photograph government buildings or airports." },
      { mark: "care", topic: "Ramadan", text: "During Ramadan, avoid eating/drinking in public by day; evenings become festive after iftar." },
      { mark: "no", topic: "Public behavior", text: "Public displays of affection, profanity and public intoxication can lead to fines or arrest." },
      { mark: "no", topic: "Alcohol", text: "Only drink in licensed venues (hotels, bars). Being drunk in public is an offence." },
    ],
    goodToKnow: [
      "Friday–Saturday is the weekend; Friday prayers mean many things open after 14:30.",
      "Tipping ~10% is customary in restaurants if not included.",
      "Tap water is desalinated and safe, but bottled water is preferred by most.",
      "The Nol card covers metro, tram, buses and water taxis.",
    ],
    places: [
      { id: "d-burj", cat: "monument", name: "Burj Khalifa", desc: "828 metres of engineering ambition — observation decks on the 124th, 125th and 148th floors.", img: IMG("burj"), rating: 4.7, price: "AED 169+", hours: "08:00–24:00", dist: "Downtown", lat: 25.1972, lng: 55.2744,
        artworks: [
          { name: "The Tower's Spire", period: "2004–2010", origin: "Neo-futurism", img: IMG("burj2"), sig: "Designed by Adrian Smith; over 12,000 people worked on its construction.", fact: "It can be seen from 95 km away, and its tip can be seen from space with aid." },
        ] },
      { id: "d-al-fahidi", cat: "neighborhood", name: "Al Fahidi Historic District", desc: "Wind-tower courtyards, art cafés and the Dubai Museum inside the 1787 Al Fahidi Fort.", img: IMG("alfahidi"), rating: 4.6, price: "AED 3", hours: "08:00–20:00", dist: "Old Dubai", lat: 25.2632, lng: 55.2972 },
      { id: "d-mosque", cat: "religious", name: "Jumeirah Mosque", desc: "Dubai's most beautiful mosque, built in Fatimid style — open to non-Muslims on guided tours.", img: IMG("jumeirahmosque"), rating: 4.7, price: "AED 25 (tour)", hours: "Tours 10:00 Sat/Thu", dist: "Jumeirah", lat: 25.2340, lng: 55.2656 },
      { id: "d-gold-souk", cat: "neighborhood", name: "Gold & Spice Souks", desc: "Deira's labyrinth of gold, saffron and frankincense — haggling is the local sport.", img: IMG("souk"), rating: 4.5, price: "Free", hours: "10:00–22:00", dist: "Deira", lat: 25.2711, lng: 55.3074 },
      { id: "d-frame", cat: "monument", name: "Dubai Frame", desc: "A 150 m golden frame offering old-Dubai views on one side, new-Dubai on the other.", img: IMG("frame"), rating: 4.3, price: "AED 50", hours: "09:00–21:00", dist: "Zabeel Park", lat: 25.2357, lng: 55.3003 },
      { id: "d-museum", cat: "museum", name: "Museum of the Future", desc: "An asymmetric torus of calligraphy exploring humanity's next 50 years.", img: IMG("motf"), rating: 4.6, price: "AED 149", hours: "10:00–19:30", dist: "Sheikh Zayed Rd", lat: 25.2189, lng: 55.2824 },
    ],
    experiences: [
      { id: "dx-desert", cat: "Adventure", name: "Desert Safari & Dune Bashing", desc: "4x4 dunes, camel rides, falconry and a Bedouin-style dinner under stars.", img: IMG("desert"), rating: 4.8, price: "AED 250", hours: "15:00–21:00 tours", dist: "Lahbab Desert", lat: 24.9000, lng: 55.6000 },
      { id: "dx-aquarium", cat: "Entertainment", name: "Dubai Aquarium & Underwater Zoo", desc: "10M-litre tank with sharks and rays — walk through the tunnel.", img: IMG("dubaiaqua"), rating: 4.5, price: "AED 199", hours: "10:00–22:00", dist: "Dubai Mall", lat: 25.1975, lng: 55.2796 },
      { id: "dx-marina", cat: "Nature", name: "Dubai Marina Walk & Cruise", desc: "A 7 km canal-side promenade of superyachts and towers; dhow dinner cruises at dusk.", img: IMG("marina"), rating: 4.6, price: "Free", hours: "Always open", dist: "Marina", lat: 25.0805, lng: 55.1403 },
      { id: "dx-skydive", cat: "Adventure", name: "Skydiving over Palm Jumeirah", desc: "The world's most scenic tandem jump — an artificial island below your feet.", img: IMG("skydive"), rating: 4.9, price: "AED 2,499", hours: "08:00–16:00", dist: "Palm Jumeirah", lat: 25.0990, lng: 55.1780 },
      { id: "dx-global", cat: "Entertainment", name: "Global Village", desc: "90-country pavilions of food, crafts and rides — winter's biggest fair.", img: IMG("globalvillage"), rating: 4.4, price: "AED 25", hours: "16:00–00:00", dist: "Sheikh Mohammed Bin Zayed Rd", lat: 25.0681, lng: 55.3044 },
      { id: "dx-safari-park", cat: "Family", name: "Dubai Safari Park", desc: "3,000 animals across African, Asian and Arabian villages on 119 hectares.", img: IMG("safaripark"), rating: 4.4, price: "AED 50", hours: "09:00–17:00", dist: "Al Warqa", lat: 25.1650, lng: 55.4060 },
    ],
    hotels: [
      { id: "dh-burj-al-arab", name: "Burj Al Arab Jumeirah", stars: 5, rating: 9.5, price: 1500, dist: "Jumeirah Beach", area: "Jumeirah", amenities: ["Private beach", "Butler", "Helipad", "Spa"], img: IMG("burjalarab") },
      { id: "dh-address", name: "Address Downtown", stars: 5, rating: 9.0, price: 380, dist: "0.3 km", area: "Downtown", amenities: ["Pool", "Spa", "Burj view"], img: IMG("address") },
      { id: "dh-rove", name: "Rove Downtown", stars: 3, rating: 8.6, price: 95, dist: "0.5 km", area: "Downtown", amenities: ["Pool", "Wi-Fi", "24h gym"], img: IMG("rove") },
      { id: "dh-mariott", name: "Marriott Harbour Hotel", stars: 4, rating: 8.3, price: 150, dist: "Marina", area: "Dubai Marina", amenities: ["Pool", "Breakfast", "Beach access"], img: IMG("marriothotel") },
      { id: "dh-al-seef", name: "Al Seef Heritage Hotel", stars: 4, rating: 8.5, price: 120, dist: "Creek", area: "Al Seef", amenities: ["Waterfront", "Breakfast"], img: IMG("alseef") },
      { id: "dh-ibis", name: "Ibis Al Barsha", stars: 2, rating: 7.8, price: 55, dist: "Sheikh Zayed Rd", area: "Al Barsha", amenities: ["Wi-Fi", "Metro access"], img: IMG("ibis") },
    ],
    hospitals: [
      { name: "Dubai Hospital", type: "Hospital · ER", address: "Al Khaleej Rd", lat: 25.2690, lng: 55.3090, open: "24/7" },
      { name: "American Hospital Dubai", type: "Hospital · ER", address: "Oud Metha Rd", lat: 25.2450, lng: 55.3200, open: "24/7" },
      { name: "Boots Pharmacy — Dubai Mall", type: "Pharmacy", address: "Dubai Mall, LG", lat: 25.1972, lng: 55.2797, open: "10:00–24:00" },
      { name: "Al Muraqqabat Police Station", type: "Police", address: "Deira", lat: 25.2605, lng: 55.3260, open: "24/7" },
    ],
    news: [
      { cat: "Events", title: "Dubai Fitness Challenge returns — 30 minutes × 30 days", src: "Dubai Media Office", time: "2026-10-02T07:00:00Z", img: IMG("fitness"), sum: "City-wide free classes and a weekend festival at Expo City kick off October 26." },
      { cat: "Travel", title: "Museum of the Future opens 'AI & You' permanent gallery", src: "Gulf Travel News", time: "2026-09-29T12:00:00Z", img: IMG("motf2"), sum: "The new floor lets visitors converse with historical figures via generative AI." },
      { cat: "Safety", title: "Heat stress campaign: hydration stations across tourist areas", src: "Dubai Civil Defence", time: "2026-10-04T09:30:00Z", img: IMG("heat"), sum: "Free chilled water stations installed at beaches, souks and transit stops through October." },
      { cat: "Transport", title: "Blue Line metro extension breaks ground", src: "RTA Bulletin", time: "2026-09-26T10:00:00Z", img: IMG("metro-blue"), sum: "The 30 km line will add 14 stations; completion expected 2029." },
    ],
    events: [
      { day: "26–30", mon: "Oct", title: "Dubai Fitness Challenge Festival", where: "Expo City", time: "08:00–22:00", price: "Free", cat: "Sports" },
      { day: "1–3", mon: "Nov", title: "Dubai Opera — Arabic Classics Night", where: "Dubai Opera", time: "20:00", price: "AED 350+", cat: "Concert" },
      { day: "7–9", mon: "Nov", title: "Art Dubai Autumn Fair", where: "Madinat Jumeirah", time: "12:00–21:00", price: "AED 60", cat: "Exhibition" },
      { day: "Every Fri", mon: "", title: "Global Village — Fireworks Night", where: "Global Village", time: "21:00", price: "AED 25 entry", cat: "Seasonal" },
    ],
  },

  {
    id: "istanbul", name: "Istanbul", country: "Türkiye", countryCode: "TR",
    lat: 41.0082, lng: 28.9784, tz: "Europe/Istanbul", currency: "TRY", language: "Turkish",
    languageCode: "tr", flag: "🇹🇷", population: "15.8M", plug: "Type C/F · 230V",
    emergency: { police: "155", ambulance: "112", fire: "110", general: "112" },
    visa: "e-Visa available for 90+ nationalities (~$50); some nationalities visa-free 90 days.",
    tagline: "Where two continents meet — Byzantine domes, Ottoman palaces and the Bosphorus breeze.",
    hero: IMG("voyara-istanbul", 1800, 1000),
    score: { safety: 70, weather: 72, cost: 78, attractions: 93, access: 85 },
    bestSeason: "April – June",
    monthScores: [2,3,3,4,4,3,2,2,3,3,3,2],
    monthLabels: ["Chilly","Cool","Mild","Ideal","Ideal","Pleasant","Warm","Warm","Pleasant","Mild","Cool","Rainy"],
    costBase: { hotel: [45, 110, 380], food: [20, 40, 95], transport: 4, attractions: 15, activities: 30, shopping: 25 },
    weatherSeed: { temp: 18, condition: "Light Rain", icon: "🌦️", humidity: 74, wind: 22, vis: 8, sunrise: "07:05", sunset: "18:36" },
    safety: {
      level: "yellow", label: "Exercise Caution",
      advisory: "Exercise increased caution. Protests occasionally occur in Taksim and Kadıköy — avoid demonstrations. Petty theft is common in tourist zones.",
      source: "Demo advisory · verify with your foreign ministry",
      updated: "2026-10-05T09:00:00Z",
      alerts: [
        { sev: "yellow", title: "Planned demonstration, Taksim", text: "A march is announced for Saturday afternoon. Taksim Square and Istiklal may see crowd restrictions.", where: "Beyoğlu", time: "2026-10-06T08:00:00Z", src: "Governorship notice" },
        { sev: "green", title: "Metro, tram & ferries normal", text: "All lines operating; Bosphorus ferries on schedule.", where: "City-wide", time: "2026-10-05T07:45:00Z", src: "IETT" },
        { sev: "yellow", title: "Earthquake preparedness", text: "Istanbul sits near the North Anatolian Fault. Know your hotel's assembly point; 'e-Deprem' app recommended.", where: "Marmara region", time: "2026-09-20T06:00:00Z", src: "AFAD" },
      ],
    },
    transport: {
      airports: [{ name: "Istanbul Airport (IST)", status: "open", note: "Europe's busiest hub, fully operational. Metro M11 connects to city." }],
      trains: "Marmaray cross-continent rail normal; metro expansion works at night on M7.",
      summary: "You can travel to Istanbul right now — airport open, public transport normal. Avoid announced demonstration areas.",
    },
    etiquette: [
      { mark: "ok", topic: "Greetings", text: "“Merhaba” works everywhere. A handshake is standard; close friends may cheek-kiss." },
      { mark: "ok", topic: "Hospitality", text: "If offered tea (çay), accepting is a warm gesture — it's how business and friendship begin." },
      { mark: "care", topic: "Mosques", text: "Women should carry a scarf for mosque visits; everyone removes shoes. Avoid visiting during Friday prayer (13:00–14:30)." },
      { mark: "care", topic: "Haggling", text: "Expected in bazaars — start ~40% below asking and keep it playful. Fixed prices in normal shops." },
      { mark: "no", topic: "Politics", text: "Avoid debating Kurdish, Armenian or Cyprus topics with strangers — deeply sensitive." },
      { mark: "no", topic: "Gestures", text: "The 'OK' sign and pointing your soles at people are offensive. Don't blow your nose loudly at the table." },
    ],
    goodToKnow: [
      "Get an Istanbulkart — it covers metro, tram, ferry and bus at big discounts.",
      "Ferries are both transport and sightseeing: take the Kadıköy line at sunset.",
      "Tap water is treated but most locals drink bottled.",
      "Friday is the main prayer day; some shops open late morning.",
    ],
    places: [
      { id: "i-ayasofya", cat: "religious", name: "Hagia Sophia", desc: "1,500 years of history — church, mosque, museum, mosque again — crowned by a 31 m dome that seemed to float.", img: IMG("ayasofya"), rating: 4.8, price: "Free (upper gallery ticket)", hours: "09:00–19:00", dist: "Sultanahmet", lat: 41.0086, lng: 28.9802, unesco: true,
        artworks: [
          { name: "The Great Dome", period: "537 AD", origin: "Byzantine, under Justinian I", img: IMG("dome"), sig: "The largest cathedral on Earth for nearly 1,000 years; its geometry still amazes engineers.", fact: "Forty windows at the dome's base make it appear to hover — locals called it 'floating in the air'." },
          { name: "Byzantine Mosaics", period: "9th–13th c.", origin: "Macedonian & Komnenian eras", img: IMG("mosaic"), sig: "Gold mosaics of emperors and the Virgin, plastered over in the Ottoman era and restored in 1934.", fact: "The Deësis mosaic was hidden behind plaster for over 500 years before being uncovered." },
        ] },
      { id: "i-topkapi", cat: "ancient", name: "Topkapi Palace", desc: "Seat of Ottoman sultans for 400 years — harems, holy relics and 86-carat diamonds.", img: IMG("topkapi"), rating: 4.7, price: "₺1,500", hours: "09:00–18:00 (Tue closed)", dist: "0.6 km", lat: 41.0115, lng: 28.9833, unesco: true,
        artworks: [
          { name: "The Spoonmaker's Diamond", period: "17th century", origin: "Ottoman treasury", img: IMG("kasikci"), sig: "An 86-carat pear-shaped diamond surrounded by 49 smaller stones.", fact: "Legend says a fisherman traded it for three spoons, unaware of its value." },
          { name: "Topkapi Dagger", period: "1747", origin: "Ottoman court craftsmanship", img: IMG("hançer"), sig: "Encrusted with emeralds; star of the 1964 heist film 'Topkapi'.", fact: "It was a gift intended for the Shah of Persia, who died before it arrived." },
        ] },
      { id: "i-sultanahmet", cat: "religious", name: "Blue Mosque", desc: "Six minarets, 20,000 Iznik tiles and a cascade of domes facing Hagia Sophia.", img: IMG("bluemosque"), rating: 4.7, price: "Free", hours: "08:30–19:00 (closed at prayers)", dist: "Sultanahmet", lat: 41.0054, lng: 28.9768 },
      { id: "i-basilica", cat: "ancient", name: "Basilica Cistern", desc: "A 6th-century underground cathedral of water, lit columns and Medusa heads.", img: IMG("cistern"), rating: 4.6, price: "₺600", hours: "09:00–22:00", dist: "0.3 km", lat: 41.0083, lng: 28.9778 },
      { id: "i-grandbazaar", cat: "neighborhood", name: "Grand Bazaar", desc: "One of the world's oldest covered markets — 4,000 shops of carpets, lamps and gold.", img: IMG("bazaar"), rating: 4.5, price: "Free", hours: "09:00–19:00 (Sun closed)", dist: "2.4 km", lat: 41.0107, lng: 28.9681 },
      { id: "i-dolmabahce", cat: "ancient", name: "Dolmabahçe Palace", desc: "The Ottoman Empire's answer to Versailles — crystal staircase and 4.5-ton chandelier.", img: IMG("dolmabahce"), rating: 4.6, price: "₺1,050", hours: "09:00–17:00 (Mon closed)", dist: "5.2 km", lat: 41.0392, lng: 29.0005 },
    ],
    experiences: [
      { id: "ix-bosphorus", cat: "Adventure", name: "Bosphorus Sunset Cruise", desc: "Sail between two continents past palaces, fortresses and waterside yalıs.", img: IMG("bosphorus"), rating: 4.8, price: "₺650", hours: "Sunset departures", dist: "Kabataş pier", lat: 41.0340, lng: 28.9950 },
      { id: "ix-hammam", cat: "Entertainment", name: "Historic Hammam Ritual", desc: "Scrub, foam massage and tea in a 16th-century bathhouse.", img: IMG("hammam"), rating: 4.7, price: "₺1,800", hours: "08:00–22:00", dist: "Cemberlitas", lat: 41.0080, lng: 28.9710 },
      { id: "ix-taksim", cat: "Nightlife", name: "Istiklal Street & Meze Night", text: "", desc: "From meyhanes in Asmalımescit to rooftop bars over the Bosphorus.", img: IMG("istiklal"), rating: 4.5, price: "₺900+", hours: "Evenings", dist: "Beyoğlu", lat: 41.0360, lng: 28.9850 },
      { id: "ix-princes", cat: "Nature", name: "Princes' Islands Day Trip", desc: "Car-free islands of Ottoman villas — rent a bike, eat ice cream, hear silence.", img: IMG("islands"), rating: 4.6, price: "₺180 ferry", hours: "Ferries hourly", dist: "Sea of Marmara", lat: 40.8760, lng: 29.0920 },
      { id: "ix-whirling", cat: "Entertainment", name: "Whirling Dervishes Ceremony", desc: "The Sema ritual of the Mevlevi order — spinning prayer set to ney flute.", img: IMG("sema"), rating: 4.8, price: "₺1,200", hours: "19:00 / 21:00", dist: "Sirkeci", lat: 41.0130, lng: 28.9760 },
      { id: "ix-aquarium", cat: "Family", name: "Istanbul Aquarium", desc: "16 themed zones from the Black Sea to the Pacific, with a rainforest.", img: IMG("istakvaryum"), rating: 4.4, price: "₺950", hours: "10:00–20:00", dist: "Florya", lat: 40.9670, lng: 28.7880 },
    ],
    hotels: [
      { id: "ih-ciragan", name: "Çırağan Palace Kempinski", stars: 5, rating: 9.2, price: 850, dist: "Bosphorus", area: "Beşiktaş", amenities: ["Palace wing", "Pool", "Bosphorus view", "Spa"], img: IMG("ciragan") },
      { id: "ih-sultania", name: "Hotel Sultania Boutique", stars: 4, rating: 8.8, price: 140, dist: "0.2 km", area: "Sultanahmet", amenities: ["Rooftop", "Breakfast", "Hammam"], img: IMG("sultania") },
      { id: "ih-karakoy", name: "Karaköy Rooms", stars: 4, rating: 8.5, price: 110, dist: "Galata", area: "Karaköy", amenities: ["Design", "Breakfast", "Bar"], img: IMG("karakoy") },
      { id: "ih-nera", name: "Nera Hotel Old City", stars: 3, rating: 8.0, price: 65, dist: "0.4 km", area: "Laleli", amenities: ["Breakfast", "Wi-Fi"], img: IMG("nera") },
      { id: "ih-raffles", name: "Raffles Istanbul", stars: 5, rating: 9.0, price: 420, dist: "Zorlu Center", area: "Beşiktaş", amenities: ["Pool", "Spa", "Michelin dining"], img: IMG("raffles") },
      { id: "ih-taksim-inn", name: "Taksim Square Inn", stars: 3, rating: 7.7, price: 58, dist: "Taksim", area: "Beyoğlu", amenities: ["Wi-Fi", "Breakfast"], img: IMG("taksiminn") },
    ],
    hospitals: [
      { name: "Istanbul University-Cerrahpaşa Hospital", type: "Hospital · ER", address: "Cerrahpaşa, Fatih", lat: 41.0050, lng: 28.9400, open: "24/7" },
      { name: "American Hospital", type: "Hospital · ER", address: "Güzelbahçe Sk, Nişantaşı", lat: 41.0480, lng: 28.9950, open: "24/7" },
      { name: "Eczane (Pharmacy) — Sultanahmet", type: "Pharmacy", address: "Divan Yolu Cd.", lat: 41.0065, lng: 28.9755, open: "08:30–20:00" },
      { name: "Beyoğlu Police Station", type: "Police", address: "Şahkulu Bostan Sk.", lat: 41.0300, lng: 28.9770, open: "24/7" },
    ],
    news: [
      { cat: "Local", title: "Istanbul Modern reopens expanded waterfront building", src: "Art Review TR", time: "2026-09-27T13:00:00Z", img: IMG("istmodern"), sum: "Renzo Piano's new building doubles gallery space and adds a panoramic restaurant." },
      { cat: "Transport", title: "M11 metro to Istanbul Airport extends to city center", src: "Ulaşım Journal", time: "2026-10-02T08:00:00Z", img: IMG("m11"), sum: "Direct rail link now reaches Gayrettepe; journey time cut to 34 minutes." },
      { cat: "Events", title: "Istanbul Biennial opens along the Golden Horn", src: "Culture Weekly", time: "2026-09-20T10:00:00Z", img: IMG("biennial"), sum: "The 19th edition stages works in shipyards, warehouses and mosques through December." },
      { cat: "Safety", title: "Weekend demonstration announced in Taksim — plan routes", src: "Governorship Notice", time: "2026-10-06T08:00:00Z", img: IMG("taksim"), sum: "Authorities expect crowd restrictions around Istiklal Street Saturday afternoon." },
    ],
    events: [
      { day: "11–19", mon: "Oct", title: "Istanbul Biennial — Golden Horn venues", where: "Haliç shipyards", time: "11:00–19:00", price: "₺450", cat: "Exhibition" },
      { day: "18", mon: "Oct", title: "Whirling Dervishes at Sirkeci Station Hall", where: "Sirkeci", time: "19:00", price: "₺1,200", cat: "Cultural" },
      { day: "25", mon: "Oct", title: "Republic Day concerts & fireworks", where: "Vatan Avenue", time: "20:00", price: "Free", cat: "Public holiday" },
      { day: "Weekends", mon: "", title: "Kadıköy Street Food Festival", where: "Kadıköy market", time: "12:00–22:00", price: "Free entry", cat: "Market" },
    ],
  },

  {
    id: "rome", name: "Rome", country: "Italy", countryCode: "IT",
    lat: 41.9028, lng: 12.4964, tz: "Europe/Rome", currency: "EUR", language: "Italian",
    languageCode: "it", flag: "🇮🇹", population: "2.8M", plug: "Type C/F/L · 230V",
    emergency: { police: "113", ambulance: "118", fire: "115", general: "112" },
    visa: "Schengen — visa-free 90 days for EU/US/UK/CA/AU citizens.",
    tagline: "Every corner a ruin, every piazza a stage — twenty-eight centuries, still standing.",
    hero: IMG("voyara-rome", 1800, 1000),
    score: { safety: 74, weather: 76, cost: 52, attractions: 97, access: 86 },
    bestSeason: "April – June",
    monthScores: [2,3,4,4,4,3,2,2,3,3,2,1],
    monthLabels: ["Cool","Mild","Blossom","Ideal","Ideal","Pleasant","Hot","Hot","Pleasant","Mild","Cool","Festive"],
    costBase: { hotel: [85, 190, 520], food: [30, 58, 125], transport: 8, attractions: 20, activities: 32, shopping: 28 },
    weatherSeed: { temp: 21, condition: "Sunny", icon: "☀️", humidity: 62, wind: 11, vis: 10, sunrise: "07:12", sunset: "18:45" },
    safety: {
      level: "green", label: "Normal",
      advisory: "Exercise normal precautions. Watch for pickpockets on the metro (lines A/B), Termini station and around the Colosseum.",
      source: "Demo advisory · verify with your foreign ministry",
      updated: "2026-10-05T09:00:00Z",
      alerts: [
        { sev: "yellow", title: "Pickpocket warnings, Metro A", text: "Teams reported working Termini–Ottaviano corridor. Bags in front, zips closed.", where: "Metro Line A", time: "2026-10-03T16:00:00Z", src: "Polizia di Stato" },
        { sev: "green", title: "All monuments open normally", text: "No strikes or closures scheduled this week.", where: "City-wide", time: "2026-10-05T07:00:00Z", src: "Municipio di Roma" },
      ],
    },
    transport: {
      airports: [{ name: "Fiumicino (FCO)", status: "open", note: "All flights operating. Leonardo Express 32 min to Termini." }],
      trains: "Metro, buses and trams normal — a strike is possible late month (not yet confirmed).",
      summary: "You can travel to Rome right now — airport open, city transport normal.",
    },
    etiquette: [
      { mark: "ok", topic: "Greetings", text: "“Buongiorno” when entering any shop or bar. Italians greet before everything else." },
      { mark: "ok", topic: "Coffee", text: "Cappuccino is a morning drink only. Espresso at the bar costs less than sitting at a table." },
      { mark: "care", topic: "Churches", text: "Shoulders and knees covered to enter St Peter's and the Vatican museums." },
      { mark: "care", topic: "Dining", text: "Service (coperto) ~€2–4 is standard. A small tip (round up) is appreciated." },
      { mark: "no", topic: "Fountains", text: "Don't sit on or dip feet in historic fountains — fines up to €500." },
      { mark: "no", topic: "Sistine Chapel", text: "Photography and talking are forbidden in the Sistine Chapel." },
    ],
    goodToKnow: [
      "Drink free from the nasoni — Rome's 2,500 continuously-running fountains.",
      "Book Colosseum/Vatican tickets weeks ahead; walk-up lines waste hours.",
      "Cover shoulders for Vatican; comfortable shoes for cobblestones (sanpietrini).",
      "Many trattorias close 15:00–19:00; dinner starts after 20:00.",
    ],
    places: [
      { id: "r-colosseum", cat: "ancient", name: "Colosseum", desc: "The 50,000-seat amphitheatre of the emperors — gladiators, naval battles and 2,000 years of survival.", img: IMG("colosseum"), rating: 4.8, price: "€18", hours: "08:30–19:00", dist: "1.9 km", lat: 41.8902, lng: 12.4922, unesco: true,
        artworks: [
          { name: "The Flavian Amphitheatre", period: "70–80 AD", origin: "Roman Empire", img: IMG("colosseo2"), sig: "The largest amphitheatre ever built; a marvel of vaulted concrete engineering.", fact: "It once flooded for mock naval battles — sailors fought ships inside the arena." },
        ] },
      { id: "r-vatican", cat: "museum", name: "Vatican Museums & Sistine Chapel", desc: "Nine miles of art ending under Michelangelo's ceiling — the apex of the Renaissance.", img: IMG("vatican"), rating: 4.8, price: "€20", hours: "09:00–18:00 (Sun closed)", dist: "4.1 km", lat: 41.9065, lng: 12.4536, unesco: true, visit: "4–5 hours",
        artworks: [
          { name: "The Creation of Adam", period: "1508–1512", origin: "High Renaissance", img: IMG("adam"), sig: "Michelangelo's fresco defines the Renaissance vision of man and God.", fact: "God's touching finger is just millimetres from Adam's — never quite connecting." },
          { name: "Laocoön and His Sons", period: "c. 40–30 BC", origin: "Hellenistic Greece", img: IMG("laocoon"), sig: "The Vatican's founding masterpiece — a priest and his sons battling serpents.", fact: "It was unearthed in 1506 in a Roman vineyard; Michelangelo was called to authenticate it." },
          { name: "School of Athens", period: "1509–1511", origin: "High Renaissance", img: IMG("athens"), sig: "Raphael paints all of classical philosophy as one conversation — Plato points up, Aristotle points down.", fact: "The face of Heraclitus is a portrait of Michelangelo, painted while he worked next door." },
        ] },
      { id: "r-pantheon", cat: "ancient", name: "Pantheon", desc: "The best-preserved Roman building — a 2,000-year-old dome with a hole for a roof.", img: IMG("pantheon"), rating: 4.9, price: "€5", hours: "09:00–19:00", dist: "1.6 km", lat: 41.8986, lng: 12.4769 },
      { id: "r-trevi", cat: "monument", name: "Trevi Fountain", desc: "Baroque theatre in stone — toss a coin over your shoulder to guarantee your return.", img: IMG("trevi"), rating: 4.6, price: "Free", hours: "Always open", dist: "2.0 km", lat: 41.9009, lng: 12.4833 },
      { id: "r-forum", cat: "ancient", name: "Roman Forum & Palatine Hill", desc: "Walk the main street of the ancient world — basilicas, triumphal arches and Caesar's house.", img: IMG("forum"), rating: 4.7, price: "€18 (with Colosseum)", hours: "08:30–18:30", dist: "2.0 km", lat: 41.8925, lng: 12.4853, unesco: true },
      { id: "r-trastevere", cat: "neighborhood", name: "Trastevere", desc: "Ivy-draped lanes, craft shops and Rome's best aperitivo hour on Piazza di Santa Maria.", img: IMG("trastevere"), rating: 4.7, price: "Free", hours: "Always open", dist: "3.3 km", lat: 41.8896, lng: 12.4694 },
    ],
    experiences: [
      { id: "rx-appia", cat: "Adventure", name: "Appian Way e-Bike & Catacombs", desc: "Pedal the basalt highway of the legions, then descend into early-Christian catacombs.", img: IMG("appia"), rating: 4.8, price: "€45", hours: "09:00 / 14:30 tours", dist: "4.5 km", lat: 41.8660, lng: 12.5020 },
      { id: "rx-cooking", cat: "Nightlife", name: "Roman Pasta Cooking Class", desc: "Learn fettuccine and carbonara from a Roman nonna, then eat your homework.", img: IMG("pasta"), rating: 4.9, price: "€65", hours: "18:00–21:30", dist: "Campo de' Fiori", lat: 41.8958, lng: 12.4720 },
      { id: "rx-villaborghese", cat: "Nature", name: "Villa Borghese Gardens", desc: "Rome's green lung — rowboats, a Pincio terrace sunset and the Galleria Borghese.", img: IMG("borghese"), rating: 4.6, price: "Free", hours: "Always open", dist: "3.0 km", lat: 41.9120, lng: 12.4850 },
      { id: "rx-gelato", cat: "Family", name: "Gelato Masterclass & Tasting Trail", desc: "Churn gelato, then follow the city's best artisan gelaterie.", img: IMG("gelato"), rating: 4.7, price: "€39", hours: "15:00–18:00", dist: "Monti", lat: 41.8950, lng: 12.4930 },
      { id: "rx-opera", cat: "Entertainment", name: "Opera at Baths of Caracalla", desc: "Aida under the stars among 3rd-century ruins — summer only.", img: IMG("opera"), rating: 4.8, price: "€55+", hours: "21:00", dist: "3.8 km", lat: 41.8790, lng: 12.4920 },
      { id: "rx-zoomarine", cat: "Family", name: "Bioparco di Roma", desc: "Italy's oldest zoo, in Villa Borghese — conservation-focused and shady.", img: IMG("bioparco"), rating: 4.2, price: "€16", hours: "09:30–18:00", dist: "3.2 km", lat: 41.9160, lng: 12.4880 },
    ],
    hotels: [
      { id: "rh-hassler", name: "Hassler Roma", stars: 5, rating: 9.1, price: 1450, dist: "Top of Spanish Steps", area: "Piazza di Spagna", amenities: ["Spa", "Michelin dining", "Historic"], img: IMG("hassler") },
      { id: "rh-artemide", name: "Hotel Artemide", stars: 4, rating: 8.8, price: 210, dist: "0.4 km", area: "Via Nazionale", amenities: ["Rooftop bar", "Spa", "Breakfast"], img: IMG("artemide") },
      { id: "rh-trastevere", name: "Trastevere Relais", stars: 3, rating: 8.3, price: 130, dist: "3.1 km", area: "Trastevere", amenities: ["Breakfast", "Wi-Fi"], img: IMG("trasteverehotel") },
      { id: "rh-condotti", name: "Hotel Condotti", stars: 3, rating: 8.0, price: 155, dist: "0.2 km", area: "Via Condotti", amenities: ["Wi-Fi", "Bar"], img: IMG("condotti") },
      { id: "rh-agrippa", name: "Pantheon Agrippa Inn", stars: 2, rating: 7.7, price: 95, dist: "1.5 km", area: "Pantheon", amenities: ["Wi-Fi", "Breakfast"], img: IMG("agrippa") },
      { id: "rh-stgeorge", name: "St. George Roma", stars: 5, rating: 8.9, price: 520, dist: "2.3 km", area: "Via Giulia", amenities: ["Spa", "Pool", "Rooftop"], img: IMG("stgeorge") },
    ],
    hospitals: [
      { name: "Policlinico Umberto I", type: "Hospital · ER", address: "Viale del Policlinico 155", lat: 41.9060, lng: 12.5110, open: "24/7" },
      { name: "Ospedale Santo Spirito", type: "Hospital · ER", address: "Lungotevere in Sassia 1", lat: 41.9010, lng: 12.4590, open: "24/7" },
      { name: "Farmacia del Senato", type: "Pharmacy", address: "Piazza di Monte Citorio", lat: 41.9000, lng: 12.4760, open: "08:30–20:00" },
      { name: "Questura di Roma", type: "Police", address: "Via San Vitale 15", lat: 41.8950, lng: 12.5020, open: "24/7" },
    ],
    news: [
      { cat: "Events", title: "Rome Film Fest opens on Via Veneto", src: "La Cultura", time: "2026-10-04T09:00:00Z", img: IMG("filmfest"), sum: "Red carpet through October 19 with open-air screenings at Auditorium Parco della Musica." },
      { cat: "Travel", title: "Colosseum's underground tunnels open fully to public", src: "Archeo News", time: "2026-09-26T11:30:00Z", img: IMG("hypogeum"), sum: "The full hypogeum route with the reconstructed lift platform is now bookable." },
      { cat: "Local", title: "Jubilee 2026 legacy: new pilgrim trails across Rome", src: "Il Giornale", time: "2026-09-30T07:45:00Z", img: IMG("jubilee"), sum: "Renovated pilgrim hostels and signage remain open along the Via Francigena." },
      { cat: "Weather", title: "October heatwave: 27°C forecast through the weekend", src: "Meteo Italia", time: "2026-10-05T05:00:00Z", img: IMG("romasun"), sum: "Unseasonably warm 'ottobrata' days perfect for outdoor sites." },
    ],
    events: [
      { day: "16–26", mon: "Oct", title: "Rome Film Fest", where: "Auditorium Parco della Musica", time: "Various", price: "€12+", cat: "Festival" },
      { day: "31", mon: "Oct", title: "Halloween Night at Castel Sant'Angelo", where: "Castel Sant'Angelo", time: "20:00–24:00", price: "€25", cat: "Seasonal" },
      { day: "1", mon: "Nov", title: "All Saints' Day — museums open, many offices closed", where: "City-wide", time: "All day", price: "—", cat: "Public holiday" },
      { day: "Weekends", mon: "", title: "Vintage market at Mercato di Testaccio", where: "Testaccio", time: "09:00–15:00", price: "Free", cat: "Market" },
    ],
  },

  {
    id: "newyork", name: "New York City", country: "United States", countryCode: "US",
    lat: 40.7128, lng: -74.0060, tz: "America/New_York", currency: "USD", language: "English",
    languageCode: "en", flag: "🇺🇸", population: "8.3M", plug: "Type A/B · 120V",
    emergency: { police: "911", ambulance: "911", fire: "911", general: "911" },
    visa: "ESTA (visa waiver, $21) for 40 nationalities; B1/B2 visa otherwise.",
    tagline: "The vertical metropolis — five boroughs of ambition, art and 3 a.m. everything.",
    hero: IMG("voyara-nyc", 1800, 1000),
    score: { safety: 68, weather: 62, cost: 38, attractions: 95, access: 95 },
    bestSeason: "May – June",
    monthScores: [1,1,2,3,4,4,3,3,3,3,2,1],
    monthLabels: ["Freezing","Cold","Cool","Mild","Ideal","Ideal","Warm","Warm","Pleasant","Mild","Cool","Festive"],
    costBase: { hotel: [160, 320, 850], food: [45, 85, 200], transport: 15, attractions: 35, activities: 55, shopping: 40 },
    weatherSeed: { temp: 16, condition: "Scattered Clouds", icon: "🌤️", humidity: 59, wind: 18, vis: 12, sunrise: "06:54", sunset: "18:26" },
    safety: {
      level: "yellow", label: "Exercise Caution",
      advisory: "Exercise normal-to-increased caution. Violent crime is concentrated in areas tourists rarely visit; stay aware on empty subway cars at night and in Central Park after dark.",
      source: "Demo advisory · verify with your foreign ministry",
      updated: "2026-10-05T09:00:00Z",
      alerts: [
        { sev: "yellow", title: "Subway service changes, weekend", text: "Track work suspends F service between Jay St and Coney Island; use the N/Q instead.", where: "Brooklyn lines", time: "2026-10-05T05:00:00Z", src: "MTA" },
        { sev: "green", title: "Airports operating normally", text: "JFK, EWR and LGA all open; typical evening delays of 20–40 min at JFK.", where: "All NYC airports", time: "2026-10-05T07:00:00Z", src: "FAA" },
      ],
    },
    transport: {
      airports: [{ name: "JFK Intl", status: "open", note: "AirTrain + LIRR is fastest to Manhattan (35 min)." }, { name: "LaGuardia (LGA)", status: "open", note: "Fully rebuilt terminals; Q70 bus to subway." }, { name: "Newark (EWR)", status: "open", note: "NJ Transit to Penn Station, 30 min." }],
      trains: "Subway 24/7 with weekend work changes; buses and ferries normal.",
      summary: "You can travel to New York right now — all airports open. Expect weekend subway service changes.",
    },
    etiquette: [
      { mark: "ok", topic: "Pace", text: "Keep right on sidewalks and escalators, have your MetroCard/app ready, and don't stop in the middle of the flow." },
      { mark: "ok", topic: "Tipping", text: "Tipping 18–20% is essential: waiters, bartenders, taxis, hotel staff ($2–5/day). It's how people are paid." },
      { mark: "care", topic: "Small talk", text: "New Yorkers are warmer than their reputation — but brief. Direct questions get direct answers." },
      { mark: "care", topic: "Dress", text: "Anything goes, but black and layers read as local. Comfortable shoes are non-negotiable." },
      { mark: "no", topic: "Times Square", text: "Don't stop dead in the middle of the sidewalk for photos — step to the curb or a plaza." },
      { mark: "no", topic: "Empty subway cars", text: "If a car is empty at rush hour, there's a reason. Move to the next one." },
    ],
    goodToKnow: [
      "The subway runs 24/7 — the official OMNY contactless system caps weekly fares.",
      "Walk avenues north–south; crosstown buses beat long east–west walks.",
      "Many museums are 'pay what you wish' on certain evenings.",
      "Water from public fountains is clean and cold — carry a bottle.",
    ],
    places: [
      { id: "n-met", cat: "museum", name: "The Metropolitan Museum of Art", desc: "Two million works spanning 5,000 years — the encyclopaedia of human creativity.", img: IMG("themet"), rating: 4.9, price: "$30 (pay-what-you-wish for NY)", hours: "10:00–17:00 (Fri/Sat to 21:00)", dist: "8.4 km", lat: 40.7794, lng: -73.9632, visit: "3–5 hours",
        artworks: [
          { name: "Temple of Dendur", period: "10 BC", origin: "Roman Egypt", img: IMG("dendur"), sig: "A Nubian temple gifted by Egypt, installed in a glass wall facing Central Park.", fact: "It was saved from the flooding of the Nile by the Aswan Dam in the 1960s." },
          { name: "Washington Crossing the Delaware", period: "1851", origin: "American Romanticism", img: IMG("delaware"), sig: "Leutze's 3.7 m canvas turned a defeat into the founding myth of American resolve.", fact: "The flag in the painting is historically impossible — an artistic liberty." },
          { name: "Self-Portrait with a Straw Hat", period: "1887", origin: "Post-Impressionism", img: IMG("vangoghhat"), sig: "Van Gogh painted over 30 self-portraits, partly because he couldn't afford models.", fact: "The pigments he used have chemically degraded — his reds are now browns." },
        ] },
      { id: "n-liberty", cat: "monument", name: "Statue of Liberty & Ellis Island", desc: "The colossus of New York harbor and the immigration museum that tells how America was made.", img: IMG("liberty"), rating: 4.7, price: "$24.30 (ferry)", hours: "09:00–17:00", dist: "Harbor ferry", lat: 40.6892, lng: -74.0445 },
      { id: "n-centralpark", cat: "nature", name: "Central Park", desc: "843 acres of meadow, woodland and Bethesda Terrace in the middle of the grid.", img: IMG("centralpark"), rating: 4.8, price: "Free", hours: "06:00–01:00", dist: "7.9 km", lat: 40.7812, lng: -73.9665 },
      { id: "n-brooklynbridge", cat: "monument", name: "Brooklyn Bridge", desc: "Walk the 1883 Gothic arches at sunrise — the best skyline view in America.", img: IMG("brooklynbridge"), rating: 4.8, price: "Free", hours: "Always open", dist: "2.0 km", lat: 40.7061, lng: -73.9969 },
      { id: "n-highline", cat: "nature", name: "The High Line", desc: "An elevated freight rail reborn as a 2.4 km garden promenade through the Meatpacking District.", img: IMG("highline"), rating: 4.6, price: "Free", hours: "07:00–22:00", dist: "4.6 km", lat: 40.7480, lng: -74.0048 },
      { id: "n-moma", cat: "museum", name: "MoMA", desc: "The museum that defined modern art — Starry Night, Campbell's Soup and the sculpture garden.", img: IMG("moma"), rating: 4.7, price: "$30", hours: "10:30–17:30", dist: "6.8 km", lat: 40.7614, lng: -73.9776, visit: "2–3 hours",
        artworks: [
          { name: "The Starry Night", period: "1889", origin: "Post-Impressionism", img: IMG("starryny"), sig: "Painted from Van Gogh's asylum window — the view he saw vs. the sky he felt.", fact: "He considered it a failure; today it is the most recognized painting in the world." },
          { name: "Campbell's Soup Cans", period: "1962", origin: "Pop Art", img: IMG("warhol"), sig: "Warhol's 32 canvases ended the divide between commerce and high art.", fact: "He hand-painted the first set, then switched to screen printing to mimic mass production." },
        ] },
    ],
    experiences: [
      { id: "nx-topofrock", cat: "Entertainment", name: "Top of the Rock Observatory", desc: "The classic 70th-floor view — Empire State in frame, Central Park to the north.", img: IMG("topofrock"), rating: 4.7, price: "$43", hours: "09:00–23:00", dist: "6.9 km", lat: 40.7591, lng: -73.9797 },
      { id: "nx-helicopter", cat: "Adventure", name: "Manhattan Helicopter Tour", desc: "15 minutes over the skyline, Statue of Liberty and the bridges.", img: IMG("heli"), rating: 4.6, price: "$229", hours: "09:00–sunset", dist: "Downtown heliport", lat: 40.7010, lng: -74.0090 },
      { id: "nx-broadway", cat: "Entertainment", name: "Broadway Show Night", desc: "Rush tickets and TKTS booths make the Great White Way surprisingly reachable.", img: IMG("broadway"), rating: 4.8, price: "$49–199", hours: "19:00 / 13:00 matinees", dist: "Theater District", lat: 40.7590, lng: -73.9845 },
      { id: "nx-greenwich", cat: "Nightlife", name: "Greenwich Village Food & Jazz Crawl", desc: "Joe's slices, historic speakeasies and late sets at the Village Vanguard.", img: IMG("village"), rating: 4.6, price: "$85+", hours: "18:00–late", dist: "Greenwich Village", lat: 40.7336, lng: -74.0027 },
      { id: "nx-coney", cat: "Family", name: "Coney Island & Luna Park", desc: "The Cyclone, Nathan's hot dogs and a boardwalk time capsule by the sea.", img: IMG("coney"), rating: 4.4, price: "$45 (ride pass)", hours: "Weekends 12:00–20:00", dist: "24 km", lat: 40.5750, lng: -73.9810 },
      { id: "nx-chelsea", cat: "Nature", name: "Chelsea Gallery Hop", desc: "20 free contemporary galleries between 19th and 27th streets.", img: IMG("chelsea"), rating: 4.5, price: "Free", hours: "Thu–Sat 11:00–18:00", dist: "4.9 km", lat: 40.7465, lng: -74.0030 },
    ],
    hotels: [
      { id: "nh-plaza", name: "The Plaza", stars: 5, rating: 8.9, price: 1100, dist: "Central Park South", area: "Midtown", amenities: ["Historic", "Spa", "Afternoon tea"], img: IMG("plaza") },
      { id: "nh-arlo", name: "Arlo SoHo", stars: 4, rating: 8.4, price: 210, dist: "SoHo", area: "Downtown", amenities: ["Rooftop", "Bar", "Micro rooms"], img: IMG("arlo") },
      { id: "nh-pod", name: "Pod 39", stars: 3, rating: 7.8, price: 120, dist: "Murray Hill", area: "Midtown East", amenities: ["Rooftop", "Wi-Fi"], img: IMG("pod39") },
      { id: "nh-hoxton", name: "The Hoxton Williamsburg", stars: 4, rating: 8.7, price: 260, dist: "Williamsburg", area: "Brooklyn", amenities: ["Rooftop pool", "Restaurants", "River view"], img: IMG("hoxton") },
      { id: "nh-hilton", name: "Hilton Midtown", stars: 4, rating: 8.1, price: 290, dist: "0.5 km", area: "Midtown", amenities: ["Gym", "Bar", "Breakfast"], img: IMG("hiltonmid") },
      { id: "nh-hi-hostel", name: "HI NYC Hostel", stars: 2, rating: 8.2, price: 60, dist: "Upper West Side", area: "UWS", amenities: ["Kitchen", "Tours", "Wi-Fi"], img: IMG("hinyc") },
    ],
    hospitals: [
      { name: "NY-Presbyterian / Weill Cornell", type: "Hospital · ER", address: "525 E 68th St", lat: 40.7645, lng: -73.9540, open: "24/7" },
      { name: "Bellevue Hospital Center", type: "Hospital · ER", address: "462 1st Ave", lat: 40.7390, lng: -73.9750, open: "24/7" },
      { name: "Duane Reade Pharmacy — Times Sq", type: "Pharmacy", address: "1350 Broadway", lat: 40.7510, lng: -73.9880, open: "24/7" },
      { name: "Midtown South Precinct", type: "Police", address: "357 W 35th St", lat: 40.7535, lng: -73.9950, open: "24/7" },
    ],
    news: [
      { cat: "Events", title: "Village Halloween Parade returns to Sixth Avenue", src: "Gotham Weekender", time: "2026-10-03T10:00:00Z", img: IMG("halloween"), sum: "October 31 march of puppets and costumes from Canal to 16th — 2 million expected." },
      { cat: "Transport", title: "Congestion pricing cuts Midtown traffic 12% in first year", src: "City Desk", time: "2026-09-28T08:00:00Z", img: IMG("congestion"), sum: "Transit advocates push to reinvest toll revenue in 24/7 subway bus lines." },
      { cat: "Travel", title: "Summit One Vanderbilt opens 'Levitation' glass sky boxes", src: "NY Travel Post", time: "2026-09-24T13:15:00Z", img: IMG("summit"), sum: "The Midtown observation deck now suspends visitors 324 m over Madison Avenue." },
      { cat: "Weather", title: "First frost forecast upstate; city holds mild through weekend", src: "NWS New York", time: "2026-10-05T05:30:00Z", img: IMG("nyautumn"), sum: "Highs near 18°C with brilliant foliage peaking in the Hudson Valley." },
    ],
    events: [
      { day: "11", mon: "Oct", title: "Columbus Day Parade — Fifth Avenue", where: "5th Ave, 44th–72nd St", time: "11:30", price: "Free", cat: "Public holiday" },
      { day: "17–18", mon: "Oct", title: "Open House New York Weekend", where: "200+ buildings city-wide", time: "Various", price: "Free–$25", cat: "Cultural" },
      { day: "25", mon: "Oct", title: "Village Halloween Parade puppet workshops", where: "Clemente Soto Vélez", time: "14:00", price: "Free", cat: "Seasonal" },
      { day: "31", mon: "Oct", title: "Village Halloween Parade", where: "6th Ave, Canal→16th", time: "19:00", price: "Free", cat: "Festival" },
    ],
  },

  {
    id: "london", name: "London", country: "United Kingdom", countryCode: "GB",
    lat: 51.5074, lng: -0.1278, tz: "Europe/London", currency: "GBP", language: "English",
    languageCode: "en", flag: "🇬🇧", population: "8.9M", plug: "Type G · 230V",
    emergency: { police: "999", ambulance: "999", fire: "999", general: "999" },
    visa: "ETA (£10) required for visa-free nationalities; check UK gov site before travel.",
    tagline: "Royal parks and rebel art — two millennia of empire, innovation and drizzle.",
    hero: IMG("voyara-london", 1800, 1000),
    score: { safety: 78, weather: 55, cost: 35, attractions: 94, access: 94 },
    bestSeason: "May – September",
    monthScores: [1,2,2,3,4,3,3,3,3,3,2,1],
    monthLabels: ["Grey","Chilly","Cool","Fresh","Best","Pleasant","Summer","Summer","Pleasant","Mild","Damp","Festive"],
    costBase: { hotel: [110, 240, 680], food: [38, 70, 160], transport: 12, attractions: 28, activities: 42, shopping: 38 },
    weatherSeed: { temp: 13, condition: "Overcast", icon: "☁️", humidity: 78, wind: 19, vis: 9, sunrise: "07:18", sunset: "18:32" },
    safety: {
      level: "green", label: "Normal",
      advisory: "Exercise normal precautions. Keep phones secure near roadside (snatch theft from mopeds); standard big-city awareness applies.",
      source: "Demo advisory · verify with your foreign ministry",
      updated: "2026-10-05T09:00:00Z",
      alerts: [
        { sev: "yellow", title: "Phone snatch thefts near tourist spots", text: "Moped-riding thieves target phones held near the kerb. Use phones away from the road edge.", where: "West End, Shoreditch", time: "2026-10-02T15:00:00Z", src: "Met Police" },
        { sev: "green", title: "Tube & rail normal", text: "All Underground lines running; planned engineering on some weekend Overground routes.", where: "TfL network", time: "2026-10-05T06:30:00Z", src: "TfL" },
      ],
    },
    transport: {
      airports: [{ name: "Heathrow (LHR)", status: "open", note: "All terminals open; Elizabeth line 35 min to central London." }, { name: "Gatwick (LGW)", status: "open", note: "Thameslink & Gatwick Express normal." }],
      trains: "Underground and buses normal; check weekend engineering works.",
      summary: "You can travel to London right now — airports open, transport normal.",
    },
    etiquette: [
      { mark: "ok", topic: "Queuing", text: "The queue is sacred. Join the back, never push ahead, and don't 'save' large gaps." },
      { mark: "ok", topic: "Pubs", text: "Order at the bar — no table service. Tipping is small: round up or ~10% for meals." },
      { mark: "care", topic: "Small talk", text: "Weather is the national opener. Avoid cutting straight to business or personal questions." },
      { mark: "care", topic: "Escalators", text: "Stand right, walk left on the Tube. Tourists blocking the left side is the city's pet peeve." },
      { mark: "no", topic: "Tube etiquette", text: "No loud phone calls, keep backpacks off shoulders in crowded carriages, let people off first." },
      { mark: "no", topic: "Cutting queues", text: "Skipping a queue will draw instant, polite-but-lethal correction." },
    ],
    goodToKnow: [
      "Contactless cards/phones work everywhere on TfL — daily fare capping applies.",
      "Many museums (British Museum, Tate, V&A, NHM) are free.",
      "Carry a compact umbrella year-round; weather changes by the hour.",
      "Theatre 'day seats' and TKTS offer same-night discounts.",
    ],
    places: [
      { id: "lo-bm", cat: "museum", name: "British Museum", desc: "Eight million objects of human history — Rosetta Stone, Parthenon marbles and Egyptian mummies.", img: IMG("britishmuseum"), rating: 4.8, price: "Free", hours: "10:00–17:00", dist: "2.2 km", lat: 51.5194, lng: -0.1270, visit: "3–4 hours",
        artworks: [
          { name: "Rosetta Stone", period: "196 BC", origin: "Ptolemaic Egypt", img: IMG("rosetta"), sig: "The trilingual inscription that unlocked hieroglyphics and all of ancient Egypt.", fact: "Discovered by Napoleon's soldiers in 1799; deciphered by Champollion in 1822." },
          { name: "Parthenon Marbles", period: "447–432 BC", origin: "Classical Athens", img: IMG("parthenon"), sig: "Sculptures from Athena's temple — the eternal debate of museum ownership.", fact: "The frieze ran 160 m around the temple showing the Panathenaic procession." },
        ] },
      { id: "lo-tower", cat: "ancient", name: "Tower of London", desc: "William the Conqueror's fortress — crown jewels, Beefeaters and a thousand years of intrigue.", img: IMG("tower"), rating: 4.7, price: "£34.80", hours: "09:00–17:30", dist: "4.0 km", lat: 51.5081, lng: -0.0759, unesco: true },
      { id: "lo-westminster", cat: "religious", name: "Westminster Abbey", desc: "Coronation church since 1066 — Poets' Corner and the tombs of kings, scientists and writers.", img: IMG("westminster"), rating: 4.7, price: "£29", hours: "09:30–15:30", dist: "3.5 km", lat: 51.4994, lng: -0.1273, unesco: true },
      { id: "lo-buckinghampalace", cat: "monument", name: "Buckingham Palace & Changing of the Guard", desc: "The monarch's London home — 775 rooms and the most choreographed handover in the world.", img: IMG("buckingham"), rating: 4.5, price: "Free (State Rooms £30 in summer)", hours: "Guard 11:00 Mon/Wed/Fri/Sun", dist: "3.2 km", lat: 51.5014, lng: -0.1419 },
      { id: "lo-tate", cat: "museum", name: "Tate Modern", desc: "Contemporary art in a converted power station, with the Turbine Hall and river views.", img: IMG("tate"), rating: 4.6, price: "Free", hours: "10:00–18:00", dist: "3.8 km", lat: 51.5076, lng: -0.0994 },
      { id: "lo-camden", cat: "neighborhood", name: "Camden Market", desc: "Punk birthplace turned labyrinth of food stalls, vintage shops and canal-side lock.", img: IMG("camden"), rating: 4.4, price: "Free", hours: "10:00–18:00", dist: "4.7 km", lat: 51.5410, lng: -0.1465 },
    ],
    experiences: [
      { id: "lox-eye", cat: "Entertainment", name: "London Eye River Cruise Combo", desc: "The 135 m wheel plus a Thames cruise past the Houses of Parliament.", img: IMG("londoneye"), rating: 4.6, price: "£41", hours: "11:00–18:00", dist: "3.6 km", lat: 51.5033, lng: -0.1195 },
      { id: "lox-hampstead", cat: "Nature", name: "Hampstead Heath & Parliament Hill", desc: "320 hectares of wild swimming ponds and the city's finest sunset panorama.", img: IMG("hampstead"), rating: 4.7, price: "Free", hours: "Always open", dist: "7.2 km", lat: 51.5600, lng: -0.1650 },
      { id: "lox-shard", cat: "Nightlife", name: "Cocktails at The Shard", desc: "A 310 m sundowner over the whole city — smart casual, book ahead.", img: IMG("shard"), rating: 4.5, price: "£35+", hours: "17:00–late", dist: "4.2 km", lat: 51.5045, lng: -0.0865 },
      { id: "lox-westend", cat: "Entertainment", name: "West End Theatre Night", desc: "Les Misérables to Hamilton — day seats from £25 at the box office.", img: IMG("westend"), rating: 4.8, price: "£25–150", hours: "19:30", dist: "Theatreland", lat: 51.5130, lng: -0.1270 },
      { id: "lox-thames", cat: "Adventure", name: "Thames Speedboat RIB Tour", desc: "50 knots past Tower Bridge with a soundtrack — London's loudest sightseeing.", img: IMG("rib"), rating: 4.7, price: "£52", hours: "Hourly 10:00–18:00", dist: "London Bridge Pier", lat: 51.5060, lng: -0.0840 },
      { id: "lox-harrypotter", cat: "Family", name: "Warner Bros. Studio Tour — The Making of Harry Potter", desc: "The Great Hall, Diagon Alley and the actual Hogwarts model. A day trip.", img: IMG("wbstudio"), rating: 4.9, price: "£53.50", hours: "09:30–20:00", dist: "Leavesden, 30 km", lat: 51.6930, lng: -0.4200 },
    ],
    hotels: [
      { id: "lh-savoy", name: "The Savoy", stars: 5, rating: 9.3, price: 980, dist: "Strand", area: "Covent Garden", amenities: ["Historic", "Afternoon tea", "River view"], img: IMG("savoy") },
      { id: "lh-zetter", name: "The Zetter Townhouse", stars: 4, rating: 8.8, price: 230, dist: "Clerkenwell", area: "EC1", amenities: ["Cocktail bar", "Breakfast", "Design"], img: IMG("zetter") },
      { id: "lh-premier", name: "Premier Inn County Hall", stars: 3, rating: 8.4, price: 130, dist: "South Bank", area: "Lambeth", amenities: ["Breakfast", "Family rooms"], img: IMG("premierinn") },
      { id: "lh-palmcourt", name: "The Ritz London", stars: 5, rating: 9.0, price: 1250, dist: "Piccadilly", area: "Mayfair", amenities: ["Afternoon tea", "Michelin", "Spa"], img: IMG("ritz") },
      { id: "lh-generator", name: "Generator London", stars: 2, rating: 8.0, price: 42, dist: "Russell Sq", area: "Bloomsbury", amenities: ["Bar", "Wi-Fi", "Dorms"], img: IMG("generator") },
      { id: "lh-hoxton", name: "The Hoxton Holborn", stars: 4, rating: 8.6, price: 195, dist: "High Holborn", area: "Holborn", amenities: ["Restaurant", "Co-working", "Breakfast"], img: IMG("hoxtonlondon") },
    ],
    hospitals: [
      { name: "St Thomas' Hospital", type: "Hospital · ER", address: "Westminster Bridge Rd", lat: 51.4990, lng: -0.1189, open: "24/7" },
      { name: "University College Hospital", type: "Hospital · ER", address: "235 Euston Rd", lat: 51.5250, lng: -0.1340, open: "24/7" },
      { name: "Boots Pharmacy — Victoria", type: "Pharmacy", address: "Victoria Station", lat: 51.4950, lng: -0.1440, open: "07:00–23:00" },
      { name: "Charing Cross Police Station", type: "Police", address: "Agmar Rd, Fulham", lat: 51.4840, lng: -0.1940, open: "24/7" },
    ],
    news: [
      { cat: "Events", title: "Bonfire Night fireworks return to Battersea Park", src: "Londonist", time: "2026-10-03T09:00:00Z", img: IMG("bonfire"), sum: "November 5 celebrations with riverside fireworks and funfair — tickets on sale now." },
      { cat: "Travel", title: "Elizabeth line named UK's best rail service third year running", src: "City Metric", time: "2026-09-27T08:30:00Z", img: IMG("elizabeth"), sum: "98% reliability as capacity grows to 24 trains per hour." },
      { cat: "Local", title: "Night Tube extends to two more lines from December", src: "TfL Press", time: "2026-09-30T11:00:00Z", img: IMG("nighttube"), sum: "24-hour weekend service confirmed for the Metropolitan and Circle lines." },
      { cat: "Weather", title: "Storm 'Angus' brings weekend wind and rain", src: "Met Office", time: "2026-10-05T06:00:00Z", img: IMG("storm"), sum: "Amber wind warning Saturday; expect some river service suspensions." },
    ],
    events: [
      { day: "11–19", mon: "Oct", title: "BFI London Film Festival", where: "BFI Southbank & venues", time: "Various", price: "£15+", cat: "Festival" },
      { day: "25", mon: "Oct", title: "Diwali on the Square", where: "Trafalgar Square", time: "13:00–19:00", price: "Free", cat: "Cultural" },
      { day: "1", mon: "Nov", title: "All Saints' Day — normal opening hours", where: "City-wide", time: "—", price: "—", cat: "—" },
      { day: "5", mon: "Nov", title: "Bonfire Night — Battersea Park fireworks", where: "Battersea Park", time: "18:00–22:30", price: "£12", cat: "Seasonal" },
    ],
  },
];

/* extra searchable cities (lightweight, generate detail on the fly) */
const CITY_EXTRAS = [
  { id: "marrakech", name: "Marrakech", country: "Morocco", lat: 31.6295, lng: -7.9811, tz: "Africa/Casablanca", currency: "MAD", language: "Arabic", languageCode: "ar", flag: "🇲🇦", hero: IMG("voyara-marrakech", 1800, 1000), tagline: "The red city — souks, riads and the Atlas at the horizon." },
  { id: "barcelona", name: "Barcelona", country: "Spain", lat: 41.3874, lng: 2.1686, tz: "Europe/Madrid", currency: "EUR", language: "Spanish", languageCode: "es", flag: "🇪🇸", hero: IMG("voyara-barcelona", 1800, 1000), tagline: "Gaudí's dream city of curves, color and the Mediterranean." },
  { id: "cape-town", name: "Cape Town", country: "South Africa", lat: -33.9249, lng: 18.4241, tz: "Africa/Johannesburg", currency: "ZAR", language: "English", languageCode: "en", flag: "🇿🇦", hero: IMG("voyara-capetown", 1800, 1000), tagline: "Where Table Mountain meets two oceans." },
  { id: "singapore", name: "Singapore", country: "Singapore", lat: 1.3521, lng: 103.8198, tz: "Asia/Singapore", currency: "SGD", language: "English", languageCode: "en", flag: "🇸🇬", hero: IMG("voyara-singapore", 1800, 1000), tagline: "A garden city-state of hawkers, supertrees and seamless order." },
  { id: "rio", name: "Rio de Janeiro", country: "Brazil", lat: -22.9068, lng: -43.1729, tz: "America/Sao_Paulo", currency: "BRL", language: "Portuguese", languageCode: "pt", flag: "🇧🇷", hero: IMG("voyara-rio", 1800, 1000), tagline: "Beaches, samba and a Christ above it all." },
  { id: "sydney", name: "Sydney", country: "Australia", lat: -33.8688, lng: 151.2093, tz: "Australia/Sydney", currency: "AUD", language: "English", languageCode: "en", flag: "🇦🇺", hero: IMG("voyara-sydney", 1800, 1000), tagline: "Harbour light, opera sails and surf an hour from downtown." },
];

/* languages available in translator */
const LANGUAGES = [
  { code: "en", name: "English" }, { code: "fr", name: "French" }, { code: "es", name: "Spanish" },
  { code: "de", name: "German" }, { code: "it", name: "Italian" }, { code: "pt", name: "Portuguese" },
  { code: "tr", name: "Turkish" }, { code: "ar", name: "Arabic" }, { code: "fa", name: "Persian" },
  { code: "ja", name: "Japanese" }, { code: "ko", name: "Korean" }, { code: "zh", name: "Chinese" },
  { code: "hi", name: "Hindi" }, { code: "ru", name: "Russian" }, { code: "th", name: "Thai" },
];

/* handy phrases seeded per language (demo + offline fallback) */
const PHRASES = {
  en: { "Where is the nearest pharmacy?": "Where is the nearest pharmacy?", "How much does this cost?": "How much does this cost?", "I need help.": "I need help.", "Thank you very much.": "Thank you very much.", "Excuse me, where is the metro?": "Excuse me, where is the metro?" },
  fr: { "Where is the nearest pharmacy?": "Où est la pharmacie la plus proche ?", "How much does this cost?": "Combien ça coûte ?", "I need help.": "J'ai besoin d'aide.", "Thank you very much.": "Merci beaucoup.", "Excuse me, where is the metro?": "Excusez-moi, où est le métro ?" },
  es: { "Where is the nearest pharmacy?": "¿Dónde está la farmacia más cercana?", "How much does this cost?": "¿Cuánto cuesta esto?", "I need help.": "Necesito ayuda.", "Thank you very much.": "Muchas gracias.", "Excuse me, where is the metro?": "Disculpe, ¿dónde está el metro?" },
  it: { "Where is the nearest pharmacy?": "Dov'è la farmacia più vicina?", "How much does this cost?": "Quanto costa questo?", "I need help.": "Ho bisogno di aiuto.", "Thank you very much.": "Grazie mille.", "Excuse me, where is the metro?": "Mi scusi, dov'è la metropolitana?" },
  tr: { "Where is the nearest pharmacy?": "En yakın eczane nerede?", "How much does this cost?": "Bu ne kadar?", "I need help.": "Yardıma ihtiyacım var.", "Thank you very much.": "Çok teşekkür ederim.", "Excuse me, where is the metro?": "Afedersiniz, metro nerede?" },
  ar: { "Where is the nearest pharmacy?": "أين أقرب صيدلية؟", "How much does this cost?": "بكم هذا؟", "I need help.": "أحتاج إلى مساعدة.", "Thank you very much.": "شكراً جزيلاً.", "Excuse me, where is the metro?": "عفواً، أين المترو؟" },
  fa: { "Where is the nearest pharmacy?": "نزدیک‌ترین داروخانه کجاست؟", "How much does this cost?": "این چقدر هزینه دارد؟", "I need help.": "به کمک نیاز دارم.", "Thank you very much.": "خیلی ممنون.", "Excuse me, where is the metro?": "ببخشید، مترو کجاست؟" },
  ja: { "Where is the nearest pharmacy?": "一番近い薬局はどこですか？", "How much does this cost?": "これはいくらですか？", "I need help.": "助けが必要です。", "Thank you very much.": "ありがとうございます。", "Excuse me, where is the metro?": "すみません、地下鉄はどこですか？" },
  de: { "Where is the nearest pharmacy?": "Wo ist die nächste Apotheke?", "How much does this cost?": "Wie viel kostet das?", "I need help.": "Ich brauche Hilfe.", "Thank you very much.": "Vielen Dank.", "Excuse me, where is the metro?": "Entschuldigung, wo ist die U-Bahn?" },
  pt: { "Where is the nearest pharmacy?": "Onde fica a farmácia mais próxima?", "How much does this cost?": "Quanto custa isso?", "I need help.": "Preciso de ajuda.", "Thank you very much.": "Muito obrigado.", "Excuse me, where is the metro?": "Com licença, onde é o metrô?" },
};

/* AI photo-identifier demo knowledge base (keyword → identification) */
const PHOTO_KNOWLEDGE = [
  { keys: ["tower", "eiffel", "paris", "iron"], name: "Eiffel Tower", kind: "Historical monument", confidence: 92, location: "Paris, France", history: "Built 1887–1889 by Gustave Eiffel for the World's Fair. At 330 m it was the world's tallest structure for 41 years.", meaning: "The global icon of France and of industrial-age engineering — originally criticised by Parisian artists, now the most-visited paid monument on Earth.", facts: ["It sways up to 9 cm in wind", "Repainted every 7 years with 60 tonnes of paint", "It was almost demolished in 1909"], related: ["Champ de Mars", "Trocadéro Gardens", "Seine River Cruise"] },
  { keys: ["domed", "cathedral", "ayasofya", "hagia", "byzantine", "mosque", "sophia"], name: "Hagia Sophia", kind: "Religious architecture", confidence: 88, location: "Istanbul, Türkiye", history: "Completed in 537 AD under Emperor Justinian; the largest cathedral in the world for nearly 1,000 years — later a mosque, then museum, then mosque again in 2020.", meaning: "A masterpiece of Byzantine architecture whose dome seemed to contemporaries to float — it changed the course of architectural history.", facts: ["Its dome is 31 m across", "Converted into a mosque in 1453 after the Ottoman conquest", "UNESCO World Heritage since 1985"], related: ["Blue Mosque", "Basilica Cistern", "Topkapi Palace"] },
  { keys: ["colosseum", "coliseum", "amphitheatre", "gladiator", "roman", "rome"], name: "Colosseum (Flavian Amphitheatre)", kind: "Ancient site", confidence: 94, location: "Rome, Italy", history: "Built 70–80 AD under emperors Vespasian and Titus; seated 50,000 spectators for gladiator contests and public spectacles.", meaning: "The defining symbol of Imperial Rome and still the model for every modern sports stadium.", facts: ["Could be flooded for naval battles", "Had a retractable canvas roof", "Over 900,000 people died in its arena over centuries"], related: ["Roman Forum", "Palatine Hill", "Arch of Constantine"] },
  { keys: ["mona", "lisa", "leonardo", "portrait", "painting"], name: "Mona Lisa", kind: "Painting", confidence: 95, location: "Louvre Museum, Paris", history: "Painted c. 1503–1519 by Leonardo da Vinci; brought to France by the artist himself and kept by François I.", meaning: "The most famous portrait in history — its fame exploded after it was stolen in 1911.", facts: ["Painted with sfumato — no visible brushstrokes", "She has no eyebrows (debated by scholars)", "Insured for $870 million in today's value"], related: ["Louvre Museum", "Winged Victory", "Venus de Milo"] },
  { keys: ["sushi", "food", "fish", "rice", "japanese"], name: "Sushi", kind: "Food", confidence: 90, location: "Japan (global)", history: "Originally a preservation method — fish fermented in rice — that became nigiri in Edo-period Tokyo (early 1800s) as fast food.", meaning: "The emblem of Japanese culinary aesthetics: seasonality, precision and restraint.", facts: ["Nigiri was invented as street food", "Real wasabi is grated root, rarely used abroad", "Soy sauce should touch the fish, not the rice"], related: ["Tsukiji Outer Market", "Omakase restaurants", "Food etiquette guide"] },
  { keys: ["statue", "liberty", "new york", "harbor", "freedom"], name: "Statue of Liberty", kind: "Monument", confidence: 93, location: "New York Harbor, USA", history: "A gift from France in 1886 commemorating American independence and Franco-American friendship; designed by Bartholdi with Eiffel's iron framework.", meaning: "The universal symbol of welcome — 'Mother of Exiles' to 12 million immigrants who passed it entering America.", facts: ["Her full name is 'Liberty Enlightening the World'", "The seven rays represent the seven seas/continents", "She turns green from copper oxidation"], related: ["Ellis Island", "Battery Park", "Staten Island Ferry view"] },
  { keys: ["great", "wall", "china", "mountain", "fortification"], name: "The Great Wall of China", kind: "Ancient fortification", confidence: 91, location: "Northern China", history: "Built and rebuilt from the 7th century BC to the Ming dynasty (1368–1644) to protect against nomadic raids.", meaning: "The largest human-made structure and a symbol of perseverance — visible from space only with aid, despite the myth.", facts: ["Total length ~21,000 km including all branches", "Built by soldiers, peasants and prisoners", "Sticky rice mortar held Ming-era bricks together"], related: ["Mutianyu section", "Badaling section", "Jiankou wild wall"] },
  { keys: ["pyramid", "egypt", "giza", "sphinx", "pharaoh"], name: "Great Pyramid of Giza", kind: "Ancient site", confidence: 92, location: "Giza, Egypt", history: "Built c. 2560 BC for Pharaoh Khufu; the tallest human-made structure for 3,800 years.", meaning: "The last surviving Wonder of the Ancient World and the pinnacle of Old Kingdom engineering.", facts: ["2.3 million blocks averaging 2.5 tonnes", "Aligned to true north within 0.06 degrees", "Originally faced in smooth white limestone"], related: ["Sphinx", "Solar Boat Museum", "Saqqara"] },
  { keys: ["pisa", "leaning", "tower", "campanile", "bell"], name: "Leaning Tower of Pisa", kind: "Monument", confidence: 94, location: "Pisa, Italy", history: "Construction began in 1173; the soft ground made it lean by the time builders reached the third floor.", meaning: "The world's most famous engineering mistake — proof that imperfection can become iconic.", facts: ["Currently leans ~4 degrees after stabilization", "Took 199 years to build across three wars", "Galileo allegedly dropped balls from its top"], related: ["Pisa Cathedral", "Piazza dei Miracoli", "Camposanto"] },
  { keys: ["buddha", "temple", "statue", "kyoto", "japan", "kinkaku", "golden"], name: "Kinkaku-ji (Golden Pavilion)", kind: "Religious architecture", confidence: 86, location: "Kyoto, Japan", history: "Originally a shogun's villa, converted to a Zen temple in the 15th century; burned by a monk in 1950 and faithfully rebuilt in 1955.", meaning: "A Zen statement on impermanence — gold against a dark pond, beauty precisely because it cannot last.", facts: ["Top two floors covered in pure gold leaf", "The arson inspired Yukio Mishima's novel", "Each floor uses a different architectural style"], related: ["Ryoan-ji rock garden", "Ginkaku-ji", "Arashiyama Bamboo Grove"] },
];

const PHOTO_FALLBACK = {
  name: "Unidentified subject", kind: "Unknown", confidence: 41,
  history: "I couldn't match this confidently. This may be a less-documented landmark, a regional variation, or an angle my reference data doesn't cover.",
  meaning: "Try a clearer, well-lit shot, or ask me in chat with more context (city, museum, nearby signs).",
  facts: ["Demo mode uses a local knowledge base — a live vision API (see js/config.js) dramatically widens recognition."],
  location: "Unknown — share your current city for a better guess", related: [],
};
